### ISSUE TITLE
NPE in createCustomTabResponseIntent

### ISSUE THREAD

**Issue by nazmul32** [AzureAD/microsoft-authentication-library-for-android#942] opened 2020-02-23 09:57 UTC
**Issue**
Please find the attached log here.

**Stacktrace**
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.anyconnect.sampleapp/com.microsoft.identity.client.BrowserTabActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity + 3126(ActivityThread.java:3126)
       at android.app.ActivityThread.handleLaunchActivity + 3269(ActivityThread.java:3269)
       at android.app.servertransaction.LaunchActivityItem.execute + 78(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks + 108(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute + 68(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage + 1960(ActivityThread.java:1960)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 7094(ActivityThread.java:7094)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 494(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main + 975(ZygoteInit.java:975)

**Stacktrace**
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
       at android.content.ComponentName.<init> + 131(ComponentName.java:131)
       at android.content.Intent.<init> + 6751(Intent.java:6751)
       at com.microsoft.identity.common.internal.providers.oauth2.AuthorizationFragment.createCustomTabResponseIntent + 185(AuthorizationFragment.java:185)
       at com.microsoft.identity.client.BrowserTabActivity.onCreate + 67(BrowserTabActivity.java:67)
       at android.app.Activity.performCreate + 7340(Activity.java:7340)
       at android.app.Activity.performCreate + 7331(Activity.java:7331)
       at android.app.Instrumentation.callActivityOnCreate + 1275(Instrumentation.java:1275)
       at android.app.ActivityThread.performLaunchActivity + 3106(ActivityThread.java:3106)
       at android.app.ActivityThread.handleLaunchActivity + 3269(ActivityThread.java:3269)
       at android.app.servertransaction.LaunchActivityItem.execute + 78(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks + 108(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute + 68(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage + 1960(ActivityThread.java:1960)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 7094(ActivityThread.java:7094)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 494(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main + 975(ZygoteInit.java:975)

Any help will be appreciated.

**Comment by shahzaibj** [comment] 2020-02-25 00:22
@nazmul32 Do you have repro steps for this issue? Any MSAL logs you can provide us to help investigate?

**Comment by nazmul32** [comment] 2020-02-25 06:06
I found it on Crashlytics when using this library in production.

**Comment by shahzaibj** [comment] 2020-02-26 22:12
@nazmul32 I am not able to reproduce the issue, however, I feel that this issue may be related to some of the issues fixed by this PR: https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/828

We are currently going through our test pass and will be releasing the next version of MSAL with those bits later this week. I will provide an update once the release is Maven.

**Comment by shahzaibj** [comment] 2020-03-02 17:49
@nazmul32 Can you test on the latest MSAL version `1.4.0` and see if you still have the issue?

**Comment by shahzaibj** [comment] 2020-03-04 00:56
Closing this as it is expected to be fixed by MSAL 1.4.0 - @nazmul32 Feel free to reopen if you are still experiencing issues.

**Comment by pomian17** [comment] 2020-03-11 08:50
@shahzaibj Hi, I'm reopening the issue, as it occurs for me on MSAL 1.4.0. Happens after providing correct email and password on login webview. Blank screen appears and app crashes. After launching app again user is not logged in. 
Not sure about repro steps. Seems random for now. Will update if I find some way to reproduce it.

Stacktrace similar to one above:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tedee.mobile.test, PID: 25295
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.appname/com.microsoft.identity.client.BrowserTabActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2916)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1811)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6694)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
        at android.content.ComponentName.<init>(ComponentName.java:131)
        at android.content.Intent.<init>(Intent.java:6094)
        at com.microsoft.identity.client.BrowserTabActivity.onCreate(BrowserTabActivity.java:6)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2896)

**Comment by shahzaibj** [comment] 2020-03-11 16:45
@pomian17 Thanks for reporting, I have reopened the issue accordingly. I've been able to reproduce the issue and identified the cause as well. I have a fix ready and I'll share the PR with you soon. The fix is currently planned to be rolled out with the release scheduled at the end of this month.

**Comment by shahzaibj** [comment] 2020-03-13 23:18
@nazmul32 This issue will be fixed by #970. The fix is planned to be rolled out with the next release of MSAL which is currently scheduled for the end of this month.

**Comment by shahzaibj** [comment] 2020-03-13 23:19
@pomian17 , @nazmul32  This issue will be fixed by #970. The fix is planned to be rolled out with the next release of MSAL which is currently scheduled for the end of this month.

**Comment by pomian17** [comment] 2020-04-20 06:27
@shahzaibj Hi, can you please provide some update about next release of MSAL? It was scheduled to be available at the end of March. What is the current estimated date of release?

**Comment by shahzaibj** [comment] 2020-04-20 16:20
@pomian17 Hi, unfortunately we did not do a release last month as we didn't have enough capacity. We are going to have a release this month (at the end of April) and this fix will be included in that. I will provide an update here once the release is available.

**Comment by shahzaibj** [comment] 2020-04-28 00:36
@pomian17 We've fixed this in MSAL v1.5.0
https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v1.5.0

**Closed by shahzaibj** 2020-04-28 00:36 UTC
Labels: Bug - P2, Issue Triage
