### ISSUE TITLE
Strict mode: untagged sockets

### ISSUE THREAD

**Issue by guperrot** [AzureAD/microsoft-authentication-library-for-android#511] opened 2019-01-29 00:54 UTC
Use the msal library to acquire a token by any mean and it triggers this strict mode issue:

```
2019-01-28 16:53:59.657 20658-20835/com.microsoft.appcenter.sasquatch.project D/StrictMode: StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2023)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:82)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:50)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:313)
        at libcore.io.IoBridge.socket(IoBridge.java:640)
        at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:124)
        at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:128)
        at java.net.Socket.createImpl(Socket.java:489)
        at java.net.Socket.getImpl(Socket.java:552)
        at java.net.Socket.setSoTimeout(Socket.java:1180)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
        at com.microsoft.identity.common.internal.net.HttpRequest.executeHttpSend(HttpRequest.java:189)
        at com.microsoft.identity.common.internal.net.HttpRequest.sendWithRetry(HttpRequest.java:162)
        at com.microsoft.identity.common.internal.net.HttpRequest.send(HttpRequest.java:143)
        at com.microsoft.identity.common.internal.net.HttpRequest.sendGet(HttpRequest.java:134)
        at com.microsoft.identity.common.internal.providers.microsoft.azureactivedirectory.AzureActiveDirectory.performCloudDiscovery(AzureActiveDirectory.java:148)
        at com.microsoft.identity.common.internal.authorities.Authority.performCloudDiscovery(Authority.java:197)
        at com.microsoft.identity.common.internal.authorities.Authority.getKnownAuthorityResult(Authority.java:262)
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.acquireToken(LocalMSALController.java:84)
        at com.microsoft.identity.common.internal.controllers.InteractiveTokenCommand.execute(InteractiveTokenCommand.java:64)
        at com.microsoft.identity.common.internal.controllers.ApiDispatcher$1.run(ApiDispatcher.java:73)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by iambmelt** [comment] 2019-01-29 00:58
Closing as duplicate of #449 #317

**Comment by iambmelt** [comment] 2019-01-29 00:59
Thanks @guperrot for calling this out - we have an issue tracking this request already. I've closed this one and linked to the other.

**Closed by iambmelt** 2019-01-29 00:58 UTC

**Comment by guperrot** [comment] 2019-01-29 01:00
Ok it didn't show up in my search, sorry for that.
