### ISSUE TITLE
Android Emulator Authentication failed

### ISSUE THREAD

**Issue by bazted** [AzureAD/microsoft-authentication-library-for-android#294] opened 2018-06-05 10:48 UTC
I have faced really strange issue with authorization. For newly created emulator login finishes with success, but next logins are failing.  I am reporting this issue just because using real device does not face such issue. 

```
E/AuthenticationManager$a: Authentication failed
    com.microsoft.identity.client.MsalClientException: Auth failed with the error null
        at com.microsoft.identity.client.BaseRequest.performTokenRequest(BaseRequest.java:184)
        at com.microsoft.identity.client.BaseRequest$1.run(BaseRequest.java:111)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.io.EOFException
        at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:95)
        at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:199)
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
        at com.microsoft.identity.client.HttpRequest.executeHttpSend(HttpRequest.java:191)
        at com.microsoft.identity.client.HttpRequest.sendWithRetry(HttpRequest.java:157)
        at com.microsoft.identity.client.HttpRequest.send(HttpRequest.java:138)
        at com.microsoft.identity.client.HttpRequest.sendPost(HttpRequest.java:114)
        at com.microsoft.identity.client.Oauth2Client.executeHttpRequest(Oauth2Client.java:142)
        at com.microsoft.identity.client.Oauth2Client.getToken(Oauth2Client.java:77)
        at com.microsoft.identity.client.BaseRequest.performTokenRequest(BaseRequest.java:180)
        at com.microsoft.identity.client.BaseRequest$1.run(BaseRequest.java:111) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by iambmelt** [comment] 2018-06-05 15:03
Thanks for getting in touch, @bazted 

Can confirm that the device has successfully tunneled out to a network connection? In some Hyper-V environments, network tunneling can cause curious quirks which we've generally avoided by testing with physical devices.

Additionally, can you share the following details of the emulator and its runtime?

- Host OS version (E.g Windows 10, MacOS, Linux, etc)
- Host OS emulator RAM allocation (E.g 2GB, 4GB, etc)
- Host OS emulator disk space allocation
- Emulator make (E.g Google, Genymotion, Visual Studio)
- Architecture emulation/version (E.g x86, x86-64, ARM)
- Emulator OS version (E.g 7.0.0, 8.1.0)
- Build number (Under `Settings` > `System` > `About`)
- Kernel version (Under `Settings` > `System` > `About`)

And any additional details which may helpful to create a repro on our end.

**Comment by bazted** [comment] 2018-06-05 16:37
> Can you confirm that the device has successfully tunneled out to a network connection? 
Yes as Google Play and other apps have access to internet normally. The same as first authorization completes successfully. 

Host OS: Windows 10
Android Emulator Version: 27.3.5
RAM Allocation:
    Intel HAXM 4Gb,
    Emulator RAM 1,5Gb(default value in Android Studio)
Emulator disk space 2048Mb(default)
Emulator provided by official Android SDK.
Architecture: x86
Build number: OSM1.180201.007
Kernel version: 3.18.91 

I should say that it is reproducible on different APIs. Since 22 - 27. 

Thank you for fast response.

**Comment by iambmelt** [comment] 2018-06-05 18:59
@bazted Can you try setting [the following value](https://developer.android.com/guide/topics/manifest/application-element#vmSafeMode) as a property the `<application>` node of your application's `AndroidManifest.xml` and performing a clean build?

Per [this issue](https://github.com/square/okhttp/issues/1114), some users have encountered this issue when compiling with JIT enabled.

Documentation for this vm flag can be found [here](https://developer.android.com/guide/topics/manifest/application-element#vmSafeMode).

```xml
android:vmSafeMode="true"
```

such that

```xml
<application
        android:name=".AppName"
        ....
        android:vmSafeMode="true" >
```

Let me know if this does or doesn't resolve your issue. I suspect this is likely a subsystem or `Okio` issue....

**Comment by bazted** [comment] 2018-06-06 12:55
On API 27 new error message can be extracted. 
It seems that this flag had no influence on failure rates.

```
authInteractiveCallback: Authentication failed
    com.microsoft.identity.client.MsalClientException: Auth failed with the error unexpected end of stream on com.android.okhttp.Address@9810ee60
        at com.microsoft.identity.client.BaseRequest.performTokenRequest(BaseRequest.java:184)
        at com.microsoft.identity.client.BaseRequest$1.run(BaseRequest.java:111)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: unexpected end of stream on com.android.okhttp.Address@9810ee60
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
        at com.microsoft.identity.client.HttpRequest.executeHttpSend(HttpRequest.java:191)
        at com.microsoft.identity.client.HttpRequest.sendWithRetry(HttpRequest.java:157)
        at com.microsoft.identity.client.HttpRequest.send(HttpRequest.java:138)
        at com.microsoft.identity.client.HttpRequest.sendPost(HttpRequest.java:114)
        at com.microsoft.identity.client.Oauth2Client.executeHttpRequest(Oauth2Client.java:142)
        at com.microsoft.identity.client.Oauth2Client.getToken(Oauth2Client.java:77)
        at com.microsoft.identity.client.BaseRequest.performTokenRequest(BaseRequest.java:180)
        at com.microsoft.identity.client.BaseRequest$1.run(BaseRequest.java:111) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.io.EOFException: \n not found: size=0 content=...
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127) 
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737) 
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244) 
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210) 
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0) 
        at com.microsoft.identity.client.HttpRequest.executeHttpSend(HttpRequest.java:191) 
        at com.microsoft.identity.client.HttpRequest.sendWithRetry(HttpRequest.java:157) 
        at com.microsoft.identity.client.HttpRequest.send(HttpRequest.java:138) 
        at com.microsoft.identity.client.HttpRequest.sendPost(HttpRequest.java:114) 
        at com.microsoft.identity.client.Oauth2Client.executeHttpRequest(Oauth2Client.java:142) 
        at com.microsoft.identity.client.Oauth2Client.getToken(Oauth2Client.java:77) 
        at com.microsoft.identity.client.BaseRequest.performTokenRequest(BaseRequest.java:180) 
        at com.microsoft.identity.client.BaseRequest$1.run(BaseRequest.java:111) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by iambmelt** [comment] 2018-06-06 13:09
@bazted Are you using the latest version of Okio? Have you tried disabling Okio and falling back on the default Http stack?

**Comment by iambmelt** [comment] 2018-06-06 13:15
Further reading [this thread](https://github.com/square/okhttp/issues/1114) it looks like some users have had success by disabling `gzip`...

**Comment by bazted** [comment] 2018-06-07 06:15
@iambmelt  I have latest Okhttp in dependencies and it is used for other requests, but what it has to MSAL client SDK? As I see under the hood SDK is using default Http stack.

**Comment by iambmelt** [comment] 2018-06-07 15:13
The below stack trace is all - OkHttp & Okio code. Not something MSAL controls.

As this appears to affect emulators only, I'm going to tag this P3 / Investigate. If you find a solution to this issue please do share your resolution. In the meantime, I'll leave this issue open for others to contribute if they experience issues.

```java
Caused by: java.io.EOFException
        at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:95)
        at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:199)
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
```

**Comment by jthake-msft** [comment] 2018-09-12 15:56
@danieldobalian  I'm getting the same thing with our Microsoft Graph lab too. That extra switch in manifest didn't work after a clean and rebuild either.

Code is available here
https://github.com/andrewconnell/msgraph-training-android/tree/fy20198q1-refresh

use the completed project in

\Demos\04-add-msgraph


`09-12 15:51:39.891 11169-11169/com.microsoft.nativeo365calendarevents E/MainActivity: Error authenticated
    com.microsoft.identity.client.MsalClientException: Auth failed with the error unexpected end of stream on com.android.okhttp.Address@992cb20d
        at com.microsoft.identity.client.BaseRequest.performTokenRequest(BaseRequest.java:184)
        at com.microsoft.identity.client.BaseRequest$1.run(BaseRequest.java:111)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: unexpected end of stream on com.android.okhttp.Address@992cb20d
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:26)
        at com.microsoft.identity.client.HttpRequest.executeHttpSend(HttpRequest.java:191)
        at com.microsoft.identity.client.HttpRequest.sendWithRetry(HttpRequest.java:157)
        at com.microsoft.identity.client.HttpRequest.send(HttpRequest.java:138)
        at com.microsoft.identity.client.HttpRequest.sendPost(HttpRequest.java:114)
        at com.microsoft.identity.client.Oauth2Client.executeHttpRequest(Oauth2Client.java:142)
        at com.microsoft.identity.client.Oauth2Client.getToken(Oauth2Client.java:77)`

**Comment by hbogaards** [comment] 2019-02-01 13:05
> 
> The below stack trace is all - OkHttp & Okio code. Not something MSAL controls.
> 

The stacktrace is coming from `com.android.okhttp` and `com.android.okio` packages, which means the code Android has incorporated since KitKat (4.4) for its internal `HttpUrlConnection` implementation.
(see [this answer for info](https://stackoverflow.com/a/26000067/2223831))

Users of this library can't replace this internal code with newer OkHttp and/or OkIo libraries or use any of the tricks in the referenced OkHttp issues.

These exceptions are caused by something this library is doing and/or something the Azure servers are doing!

**Comment by NakulSabharwal** [comment] 2019-03-12 18:09
> com.microsoft.identity.client.MsalClientException: Auth failed with the error unexpected end of stream on com.android.okhttp.Address@9810ee60
>         at com.microsoft.identity.client.BaseRequest.performTokenRequest(BaseRequest.java:184)
>         at com.microsoft.identity.client.BaseRequest$1.run(BaseRequest.java:111)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)

I tried using v0.2.2 with compileSdkversion=27 and getting this same error when running it on emulator. But no error when running it on a real device.

**Comment by mike-clark-8192** [comment] 2019-04-16 22:19
I am pretty sure this is caused by:
File: `common/src/main/java/com/microsoft/identity/common/internal/net/HttpRequest.java` (line ~212)
Code: `urlConnection.setRequestProperty("Connection", "close");`

This code is executed in all recent releases of com.microsoft.identity:common up to the most recent release (as of this writing: v0.0.9). If I comment out this statement, I no longer get `error unexpected end of stream on com.android.okhttp.Address` while running MSAL in emulation.

Someone already commented out this code in :common branch 'dev': https://github.com/AzureAD/microsoft-authentication-library-common-for-android/commit/bd8d4b8607970c86af893598e04c1188f3a4c942 so I guess we'll just wait to see if it gets merged into a release.

Strictly this is probably a bug in okhttp and/or Android TCP emulation, not :msal or :common. But if nobody knows of a reason to explicitly request ("Connection", "close") then might as well remove it for the sake of developers working with MSAL on emulation.

**Comment by iambmelt** [comment] 2019-04-16 23:20
@mike-clark-8192 This has a high probability of shipping in our next release - as you call out, the reason this resolves issue is unclear, but our testing hasn't exposed any adverse behavior

**Comment by iambmelt** [comment] 2019-08-05 22:57
This is removed for the next release

**Closed by iambmelt** 2019-08-05 22:57 UTC
Labels: Development / Non-Prod, P3
