### ISSUE TITLE
Back button not working for the second and following times

### ISSUE THREAD

**Issue by Chomui** [AzureAD/microsoft-authentication-library-for-android#981] opened 2020-03-26 11:07 UTC
**Smartphone:**
 - Device: Sony Xperia Z5 Compact(Android 7.1.1/API 25)/Emulator Pixel 3a (Android 5.0/API 21)
 - authorization_user_agent: with "DEFAULT" browser(Chrome) and also with "WEBVIEW"
 - MSAL Version: 1.4.0

**To Reproduce**
1. Open application
2. Tap on login button in Get started screen(my app)
3. Tap on back button in MSAL login screen
4. Tap on login button in Get started screen(my app)
5. Tap on back button in MSAL login screen - do nothing. I can comeback with phone back button, but it isn't a solution

**Expected behavior**
1. Open application
2. Tap on login button in Get started screen(my app)
3. Tap on back button in MSAL screen
4. Tap on login button in Get started screen(my app)
5. Tap on back button in MSAL screen
6. Get started screen is opened
7. Open MSAL login and comeback for the third time and etc.

**Comment by shahzaibj** [comment] 2020-03-26 17:49
@Chomui From your description, it seems like the phone back button is working properly but some other back button is not working. Can you elaborate more on exactly which back button is not working?

**Comment by Chomui** [comment] 2020-03-26 22:11
> @Chomui From your description, it seems like the phone back button is working properly but some other back button is not working. Can you elaborate more on exactly which back button is not working?

Back button that is located in the site that Authorization screen open. In this screen you have a field to write your email account and also you have two buttons below such as Next and Back.

**Comment by Chomui** [comment] 2020-03-26 22:25
I think that there is some cache that need to be remove but it doesn't. I had an another bug because of it(I couldn't login for the second time and got exception like "/common" word can't be used, but i didn't added... i fixed it in a tricky way by moving from MyOrg to MultiOrg, but it the another history...)

**Comment by shahzaibj** [comment] 2020-03-26 22:32
@Chomui So I just tried on my Pixel 2 and can't reproduce the issue with back button on my device. I am always able to successfully go back to the app by pressing the back button in the login page. There may be something special going on in the Xperia device. I'll see if I can find something like that to test on. 

In regards to your second issue that says "/common" can't be used, that's probably because you were MyOrg audience initially and MyOrg expects a tenant id instead of common as the audience. When you declared the Authority, did you specify the tenant id for your org?

**Comment by Chomui** [comment] 2020-03-26 22:40
I've added tenant id to authority, tried to add just tenant id and also tried mix(authority url with tenant id and also tenant id separately)

**Comment by Chomui** [comment] 2020-03-26 22:42
> @Chomui So I just tried on my Pixel 2 and can't reproduce the issue with back button on my device. I am always able to successfully go back to the app by pressing the back button in the login page. There may be something special going on in the Xperia device. I'll see if I can find something like that to test on.
> 
> In regards to your second issue that says "/common" can't be used, that's probably because you were MyOrg audience initially and MyOrg expects a tenant id instead of common as the audience. When you declared the Authority, did you specify the tenant id for your org?

Our QA on a project also has the bug with back button. But i don't now what them used.

**Comment by shahzaibj** [comment] 2020-03-26 22:46
@Chomui The Authority needs to be declared in the configuration something like this:

`"authorities" : [
    {
      "type": "AAD",
    "audience": {
        "type": "AzureADMyOrg",
        "tenantId": "contoso.com" // Provide your specific tenant ID here
      }
    }
  ]`

We have a document on this over here: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration

Does that help?

**Comment by Chomui** [comment] 2020-03-26 22:48
I used the documentation when was implementing MSAL. With the example you brought i had an exception - "tenant id is null", i how it can be if i put it to audience

**Comment by shahzaibj** [comment] 2020-03-26 22:51
@Chomui Actually I think our documentation is slightly incorrect here. The tenant id needs to be declared in the config as `tenant_id` instead of `tenantId`.

So it would be something like this:

```json
"authorities" : [
    {
      "type": "AAD",
    "audience": {
        "type": "AzureADMyOrg",
        "tenant_id": "<your-tenant-id>"
      }
    }
  ]
```

Can you try that out?

**Comment by Chomui** [comment] 2020-03-26 22:52
Ok, i'll try

**Comment by Chomui** [comment] 2020-03-27 09:20
> @Chomui Actually I think our documentation is slightly incorrect here. The tenant id needs to be declared in the config as `tenant_id` instead of `tenantId`.
> 
> So it would be something like this:
> 
> ```json
> "authorities" : [
>     {
>       "type": "AAD",
>     "audience": {
>         "type": "AzureADMyOrg",
>         "tenant_id": "<your-tenant-id>"
>       }
>     }
>   ]
> ```
> 
> Can you try that out?

I used this construction. So i removed authority_url and put tenant_id with "/oauth2/v2.0/authorize" endpoint and saw just white screen, after that i used without endpoint, just tenant_id and it worked and it's working now!!!

So now i can you use both AzureADMyOrg and AzureADMultipleOrgs and there is no bug with the back button, it also helped somehow. 

I think this page issues can also mark, that it's helps also with "/common endpoint" problem

**Comment by shahzaibj** [comment] 2020-03-27 15:48
@Chomui I'm glad it worked for you. In general, the `tenant_id` is not supposed to combined with the endpoint. Once you provide `tenant_id`, MSAL library computes the endpoint itself internally so the user/developer doesn't need to provide it. Since both of your issues are resolved, I'll go ahead and close this issue. We'll also work on fixing our documentation around `tenant_id`. Thanks!

**Closed** 2020-03-27 15:48 UTC
Labels: More Info
