### ISSUE TITLE
set/prefill username and password programmatically

### ISSUE THREAD

**Issue by mcelotti** [AzureAD/microsoft-authentication-library-for-android#848] opened 2019-12-03 12:11 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to set username and password programmatically so that user can have those fields pre-filled.

**Describe the solution you'd like**
A hint about how this could be achieved

**Describe alternatives you've considered**
ND

**Additional context**
ND

**Comment by iambmelt** [comment] 2019-12-03 17:16
Hi @mcelotti 

The user's email/upn can be prepopulated by setting a `login_hint` on the `AcquireTokenParameters`. Docs [here](https://javadoc.io/static/com.microsoft.identity.client/msal/1.0.0-hf1/com/microsoft/identity/client/AcquireTokenParameters.Builder.html#withLoginHint-java.lang.String-).

Example code:
```java
final AcquireTokenParameters params = new AcquireTokenParameters.Builder()
    .startAuthorizationFromActivity(activity)
    .withScopes(<scopes>)
    .withLoginHint(<login_hint>)
    .withPrompt(<prompt_params>)
    .withCallback(...)
    .build();

mPublicClientApplication.acquireToken(params);
```

As for the password, this is not supported _by design_ because it introduces an avenue for malicious apps to sniff the password of the user (and potentially send it off to another service/actor for evil purposes).

Hope this helps, I'm going to close this issue as done. Feel free to post back if this question isn't resolved.

/cc @daniDevX @molinaro-hub

**Closed by iambmelt** 2019-12-03 17:16 UTC
Labels: Question
