### ISSUE TITLE
Single Account PCA - calling signIn twice does not prompt for credentials both times

### ISSUE THREAD

**Issue by shoatman** [AzureAD/microsoft-authentication-library-for-android#991] opened 2020-04-01 15:30 UTC
**Describe the bug**
App is in development.  We are calling signIn on single account public client application in order to force the user to login in again when the app re-opens.

**Smartphone (please complete the following information):**
Not a device specific issue.  

**Stacktrace**
None

**To Reproduce**
Call signIn method twice.  The user is not prompted to enter their credentials twice.

**Expected behavior**
When signIn method is called twice.  The user is always expected to be prompted.

**Actual Behavior**
The user is not prompted to enter their credentials again.  (NOTE: from Shane: This is likely due to cookies in the browser/embedded web view.

**Comment by iambmelt** [comment] 2020-04-01 19:50
There's an additional issue in the method signature: the `login_hint` optional argument is listed as `@NonNull`

https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/ISingleAccountPublicClientApplication.java#L84

Will also fix in addressing this issue

**Comment by iambmelt** [comment] 2020-04-01 20:03
Confirmed that an Exception is thrown when `signIn` is called twice.

An empty (no detail message) `MsalClientException` is thrown with the error_code `invalid_parameter`

**Comment by iambmelt** [comment] 2020-04-01 23:35
>Expected behavior
When signIn method is called twice. The user is always expected to be prompted.

Doesn't this break our browser SSO story? What about apps that have already granted consent? First parties?

**Comment by iambmelt** [comment] 2020-04-01 23:37
Digging into this deeper, it looks possible to bypass adding just 1 account in SingleAccountMode if the broker is being used:
- Install broker
- Install app
- Sign-in to app (credentials added to broker)
- Uninstall app **without** calling `removeAccount()`
- Reinstall app
- Call `signIn()` again

**Comment by Chomui** [comment] 2020-04-07 10:59
I have the same bug. I added a parameter to a JSON file:
 "prompt" : "LOGIN"
But if try to login for second time - i receive an exception "invalid_parameter"
If i logout before login, i can pick an account instead of prompt to enter credentials again.

The only way - CookieManager.getInstance().removeAllCookies(null)
But it's not a solution, because i don't want to clear all WebView cookies

**Comment by Chomui** [comment] 2020-04-07 12:03
As i can see there is already pull request. I hope i can use it soon

**Comment by iambmelt** [comment] 2020-04-07 20:25
> I have the same bug. I added a parameter to a JSON file:
> "prompt" : "LOGIN"
> But if try to login for second time - i receive an exception "invalid_parameter"
> If i logout before login, i can pick an account instead of prompt to enter credentials again.
> 
> I can do - CookieManager.getInstance().removeAllCookies(null)
> But it's not a solution, because i don't want to clear all WebView cookies.
> 
> Is there a way to prompt user or i need to wait until it's fixed?

@Chomui Are you referring to the JSON document used to configure `PublicClientApplication`? If yes, `prompt` is not a property of this document and thus has no effect on the behavior of auth calls

Please see [this document](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration) for a list of configurable properties

**Comment by iambmelt** [comment] 2020-04-07 20:25
Resolved with #992

**Closed by iambmelt** 2020-04-07 20:25 UTC
Labels: Bug - P2
