### ISSUE TITLE
MSAL and AndroidX are not compatiable?

### ISSUE THREAD

**Issue by Raysapps** [AzureAD/microsoft-authentication-library-for-android#492] opened 2019-01-08 23:56 UTC
I am unable to use  active directory B2C authentication in my android project with AndroidX dependencies. The chrome browser shows  blank page when I click on Facebook sign in and I also noticed few log errors in android studio log cat  reported from msal lib.
The same project works fine without androidX dependencies.
Can someone suggest a workaround or a possible fix to resolve this issue?

**Comment by iambmelt** [comment] 2019-01-09 18:09
Duplicate of #354 and #469. Issue is known but not yet prioritized for a fix.

**Closed by iambmelt** 2019-01-09 18:09 UTC
Labels: Duplicate
