### ISSUE TITLE
Crash occurring onMAMCreate

### ISSUE THREAD

**Issue by TzGuru** [AzureAD/microsoft-authentication-library-for-android#1804] opened 2023-04-19 20:20 UTC
Describe the bug
Crash Caused by androidx.fragment.app.Fragment$k
Unable to instantiate fragment com.xxx.xxx.xxx.sx: could not find Fragment constructor
**The resulting crash is from a class being used by MSAL SDK and not the project.**, there is no any other library in the project using the nimbusds library.

<img width="967" alt="sx class causing crash" src="https://user-images.githubusercontent.com/11406179/233131435-2b12b046-84c1-4beb-9d9e-784da1ec462a.png">

Smartphone:

Device: Several, Mostly Techno and Infinix devices
Android Version: 8, 11, 12, 13
MSAL Version 4.2.0
Intune Mam Version 9.5.0

Stacktrace:

androidx.fragment.app.Fragment.instantiate (Fragment.java:67)
androidx.fragment.app.FragmentContainer.instantiate (FragmentContainer.java:8)
androidx.fragment.app.FragmentManager$3.instantiate (FragmentManager.java:8)
androidx.fragment.app.FragmentState.instantiate (FragmentState.java:2)
androidx.fragment.app.FragmentStateManager.<init> (FragmentStateManager.java:13)
androidx.fragment.app.FragmentManager.restoreSaveStateInternal (FragmentManager.java:240)
androidx.fragment.app.FragmentManager.attachController (FragmentManager.java:168)
androidx.fragment.app.FragmentController.attachHost (FragmentController.java:8)
androidx.fragment.app.FragmentActivity.lambda$init$3 (FragmentActivity.java:8)
androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable (ContextAwareHelper.java:31)
androidx.activity.ComponentActivity.onMAMCreate (ComponentActivity.java:31)
androidx.fragment.app.FragmentActivity.onMAMCreate (FragmentActivity.java:1)
com.xxx.xxx.xxx.MainActivity.onMAMCreate (MainActivity.java:1)
com.microsoft.intune.mam.client.app.offline.OfflineActivityBehavior.onCreate (OfflineActivityBehavior.java:88)
com.microsoft.intune.mam.client.app.MAMActivity.onCreate (MAMActivity.java:9)
android.app.Activity.performCreate (Activity.java:8084)
android.app.Activity.performCreate (Activity.java:8068)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1313)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3630)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3902)
android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:85)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2215)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:268)
android.app.ActivityThread.main (ActivityThread.java:8089)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:626)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:997)

**Comment by negoe** [comment] 2023-04-25 22:45
@TzGuru Can you please share what's the number of devices impacted on your side?

**Comment by TzGuru** [comment] 2023-04-26 10:15
Hi @negoe, the current version with more than 1.5k users, 137 users face this issue.

<img width="1405" alt="Screenshot 2023-04-26 at 13 11 19" src="https://user-images.githubusercontent.com/11406179/234545374-75687634-7ad3-4510-b250-d1efc6db7513.png">

**Comment by negoe** [comment] 2023-04-30 23:48
@joakley-msft Can you please let us know what exactly is happening in the code here com.microsoft.intune.mam.client.app.MAMActivity.onCreate (MAMActivity.java:9)

**Comment by joakley-msft** [comment] 2023-05-01 13:06
The Intune MAM build tooling renames `FragmentActivity.onCreate` to `FragmentActivity.onMAMCreate`. When the system calls `onCreate`, it goes to `MAMActivity.onCreate`. This locates the "behavior" which contains the implementation (strategy pattern). In this case, the Intune Company Portal, which functions as the MAM agent is not installed. MAM internally refers to this as "offline" mode, in which MAM lies dormant. `OfflineActivityBehavior.onCreate` is a passthrough which simply calls through to `FragmentActivity.onMAMCreate`. So MAM has altered the call stack, but has not actually executed any *logic* here.

Relevant documentation: https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-android-appendix#class-and-method-replacements

From the information here so far, it appears extremely unlikely that this is an Intune MAM bug. Of course if there's evidence that this occurs only after MAM SDK integration and a similar crash does not occur without MAM, we could reconsider.

**Comment by TzGuru** [comment] 2023-05-04 05:53
Hi @joakley-msft,
I have another app which has the same base code without MAM integration and has no crashes. I know this crash is difficult to trigger because all the devices i have here don’t experience it. It’s just some customers out there have devices which trigger the crash. Thats why i took the time to trace which class causes the crash and found its in the MSAL SDK.

**Comment by joakley-msft** [comment] 2023-05-15 16:37
How identical are the two apps other than MAM integration? Does this other app still use MSAL?

If you believe that this problem is being caused by Intune MAM, please file an issue at https://github.com/msintuneappsdk/ms-intune-app-sdk-android/issues, although do note that without a repro this may be challenging to diagnose

**Comment by negoe** [comment] 2023-05-15 17:18
@TzGuru Please provide the above asked details and file the issue at the new path for us to assist you further,

**Comment by negoe** [comment] 2023-05-17 05:55
@TzGuru Closing the issue for now. Please feel free to open item on the above mentioned path.

**Closed as completed by negoe** 2023-05-17 05:55 UTC
Labels: More Info, Incoming Issue
