### ISSUE TITLE
Custom webview on MSAL

### ISSUE THREAD

**Issue by xyzwilliamxyz** [AzureAD/microsoft-authentication-library-for-android#930] opened 2020-02-11 17:26 UTC
Hi!

is it possible to add a custom webview on MSAL? I mean, we have a requirement of calling native android functions for analytics from webview. 

In order to do that, we would have to declare a **Handler** and add it to the webview through **addJavascriptInterface**.

Is there a way of using exposing MSAL webview or extending it?

thanks!

**Edit:**

I saw that the method **acquireToken** from **IPublicClientApplication** has an overload that allows us to pass an activity, but I can't seem to find what exactly is expected. Maybe this can help me with what we need to achieve.

**Comment by rpdome** [comment] 2020-02-12 16:38
Hi @xyzwilliamxyz,

MSAL WebView is designed for authentication activities only. May I ask for more details on what scenario you're trying to achieve here?

Thanks,
Dome

**Comment by xyzwilliamxyz** [comment] 2020-02-12 16:51
Hi @rpdome , thanks for replying.

Sure, we would like to have analytics data on user actions, i.e. click on a button or errors handled on within the webview.

Thanks,
William

**Comment by iambmelt** [comment] 2020-02-27 17:19
This is a feature request and it has some security implications regarding exposure of web ui to programmatic access where user credentials are handled

Assigning to @hamiltonha

**Closed** 2022-07-17 23:03 UTC
Labels: Issue Triage, Enhancement, Cleanup

**Comment by gsantner** [comment] 2022-07-22 09:34
@negoe   
The issue is closed without further comment, I don't see whether this is this now implemented or not?  
Can MSAL on Android now use a assigned WebView, and how?  

On iOS/macOS there is support for that <https://docs.microsoft.com/en-us/azure/active-directory/develop/customize-webviews>, but I don't see similar possibility on Android.  
I'm not interested in injecting something into some webview. I want to place/position/size the login view/fragment **inside** my own app/activity code and it's navigation & UI.

Thank you!

**Comment by hatched-MaciejPrzybylski** [comment] 2023-05-11 10:27
Can we customise webviews on android?
