### ISSUE TITLE
Defined multiple times when R8 minify is enabled

### ISSUE THREAD

**Issue by RakeeAndroid** [AzureAD/microsoft-authentication-library-for-android#1695] opened 2022-09-19 16:59 UTC
**Describe the bug**
When building app with
```
     isMinifyEnabled = true
      proguardFiles("proguard-android-optimize.txt", "proguard-rules.pro")
```

Dependencies
```
          implementation 'com.microsoft.graph:microsoft-graph:5.19.0'
          implementation 'com.azure:azure-identity:1.5.4'
          implementation 'com.microsoft.identity.client:msal:4.0.1'
 ```

Issues when creating release build

```
      Type android.support.customtabs.ICustomTabsCallback$Stub$Proxy is defined multiple times: 
      C:\Users\cs\.gradle\caches\transforms-3\fb6d6852b1032a814a162c172458ab74\transformed\browser-1.0.0- 
      runtime.jar:android/support/customtabs/ICustomTabsCallback$Stub$Proxy.class, D:\{Project folder} 
      \app\build\intermediates\javac\productionRelease\classes\android\
      support\customtabs\ICustomTabsCallback$Stub$Proxy.class
```

Smartphone (please complete the following information):

Android Version: API 32
MSAL Version: 4.0.1

**Comment by RakeeAndroid** [comment] 2022-10-05 09:16
`./gradlew app:dependencies`   I ran this command in android studio terminal result is pasted below also let me know if I have to do something more. thank you in advance!

```
+--- com.microsoft.identity.client:msal:4.0.2
|    +--- androidx.appcompat:appcompat:1.1.0 -> 1.5.1 (*)
|    +--- androidx.browser:browser:1.0.0
|    |    +--- androidx.core:core:1.0.0 -> 1.8.0 (*)
|    |    +--- androidx.annotation:annotation:1.0.0 -> 1.3.0
|    |    +--- androidx.interpolator:interpolator:1.0.0 (*)
|    |    +--- androidx.collection:collection:1.0.0 -> 1.1.0 (*)
|    |    \--- androidx.legacy:legacy-support-core-ui:1.0.0 (*)
|    +--- com.google.code.gson:gson:2.8.9 -> 2.9.0
|    +--- com.nimbusds:nimbus-jose-jwt:9.9
|    |    \--- com.github.stephenc.jcip:jcip-annotations:1.0-1
|    +--- cz.msebera.android:httpclient:4.5.8
|    +--- androidx.constraintlayout:constraintlayout:1.1.3 -> 2.1.4 (*)
|    \--- com.microsoft.identity:common:7.0.1
|         +--- com.microsoft.identity:common4j:4.0.0
|         +--- com.microsoft.device.display:display-mask:0.3.0
|         +--- cz.msebera.android:httpclient:4.5.8
|         +--- com.nimbusds:nimbus-jose-jwt:9.9 (*)
|         +--- androidx.appcompat:appcompat:1.1.0 -> 1.5.1 (*)
|         +--- com.google.code.gson:gson:2.8.9 -> 2.9.0
|         +--- androidx.browser:browser:1.0.0 (*)
|         +--- androidx.constraintlayout:constraintlayout:1.1.3 -> 2.1.4 (*)
|         +--- com.yubico.yubikit:android:2.1.0
|         |    \--- com.yubico.yubikit:core:2.1.0
|         \--- com.yubico.yubikit:piv:2.1.0
|              \--- com.yubico.yubikit:core:2.1.0

```

**Comment by negoe** [comment] 2024-03-28 18:19
Tracked internally [Product Backlog Item 2093560](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2093560): GitHub Investigate: Defined multiple times when R8 minify is enabled #1695

**Comment by negoe** [comment] 2024-03-28 18:20
Dupe of https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1677

**Closed as completed by negoe** 2024-03-28 18:20 UTC
