### ISSUE TITLE
Attempt to invoke virtual method 'boolean com.microsoft.identity.client.AuthenticationActivity$MsalCustomTabsServiceConnection.getCustomTabsServiceIsBound()' 

### ISSUE THREAD

**Issue by bussalleu2** [AzureAD/microsoft-authentication-library-for-android#535] opened 2019-02-21 13:53 UTC
I have migrated to androidX and the sso with microsoft has stopped working. The error I receive is the following:

```
java.lang.RuntimeException: Unable to stop activity {com.civ/com.microsoft.identity.client.AuthenticationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.microsoft.identity.client.AuthenticationActivity$MsalCustomTabsServiceConnection.getCustomTabsServiceIsBound()' on a null object reference
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4035)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4084)
        at android.app.ActivityThread.-wrap24(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1622)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.microsoft.identity.client.AuthenticationActivity$MsalCustomTabsServiceConnection.getCustomTabsServiceIsBound()' on a null object reference
        at com.microsoft.identity.client.AuthenticationActivity.onStop(AuthenticationActivity.java:114)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1375)
        at android.app.Activity.performStop(Activity.java:7191)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4032)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4084) 
        at android.app.ActivityThread.-wrap24(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1622) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
2019-02-21 14:18:30.169 8597-8597/com.civ E/UncaughtException: java.lang.RuntimeException: Unable to stop activity {com.civ/com.microsoft.identity.client.AuthenticationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.microsoft.identity.client.AuthenticationActivity$MsalCustomTabsServiceConnection.getCustomTabsServiceIsBound()' on a null object reference
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4035)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4084)
        at android.app.ActivityThread.-wrap24(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1622)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.microsoft.identity.client.AuthenticationActivity$MsalCustomTabsServiceConnection.getCustomTabsServiceIsBound()' on a null object reference
        at com.microsoft.identity.client.AuthenticationActivity.onStop(AuthenticationActivity.java:114)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1375)
        at android.app.Activity.performStop(Activity.java:7191)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4032)
```

I add the library as follows:

implementation('com.microsoft.identity.client:msal:0.1.1') {
            exclude group: 'com.android.support', module: 'appcompat-v7'
        }

**Comment by iambmelt** [comment] 2019-02-21 17:52
Hi @bussalleu2 - this appears appears to be a duplicate of #354 - specifically, [this comment](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/354#issuecomment-456899351) seems to mirror your issue.

Since we have #354 already tracking this issue, I'll close this one and refer you to the other. As an FYI, there is an issue in the [Android Bug Tracker](https://issuetracker.google.com/issues/115556774) for AndroidX issues related to use of our library.

**Closed by iambmelt** 2019-02-21 17:52 UTC

**Comment by jarvisgaurav98** [comment] 2019-12-25 08:55
I still have the same issue, how do I fix this?
java.lang.RuntimeException: Unable to stop activity {com.microsoft.identity.client.AuthenticationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.microsoft.identity.client.AuthenticationActivity$MsalCustomTabsServiceConnection.getCustomTabsServiceIsBound()' on a null object reference
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4152)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4122)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4197)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:198)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:171)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.microsoft.identity.client.AuthenticationActivity$MsalCustomTabsServiceConnection.getCustomTabsServiceIsBound()' on a null object reference
        at com.microsoft.identity.client.AuthenticationActivity.onStop(AuthenticationActivity.java:114)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1433)
        at android.app.Activity.performStop(Activity.java:7371)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4144)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4122) 
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4197) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:198) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:171) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6692) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
I/Process: Sending signal. PID: 2734 SIG: 9
Disconnected from the target VM, address: 'localhost:8601', transport: 'socket'
