### ISSUE TITLE
Cannot compile with AndroidX and Instant Run

### ISSUE THREAD

**Issue by thomius** [AzureAD/microsoft-authentication-library-for-android#469] opened 2018-12-02 19:25 UTC
Related to #354

The following error is reported by Java compiler during build on a fresh project migrated to AndroidX when Instant Run is enabled: 

> java.lang.SecurityException: SHA-256 digest error for com/microsoft/identity/client/AuthenticationCallback.class

Repro:

0. Create a new Android Studio project
0. Ensure Instant Run is enabled (File > Settings > Build, Execution, Deployment > Instant Run)
0. Setup MSAL: https://github.com/AzureAD/microsoft-authentication-library-for-android
0. Debug. Things should work out fine.
0. Add the following to gradle.properties:
   - android.useAndroidX=true
   - android.enableJetifier=true
0. Refactor > Migrate to AndroidX
0. Try to start debugging
0. Now compiler reports the error mentioned above
0. Disable Instant Run
0. Debug
0. Now things work out fine.

Is there a way to get MSAL working together with Instant Run and AndroidX?

**Comment by iambmelt** [comment] 2019-01-09 18:11
Closing as duplicate of #354 - please use that issue for discussion, posting logs, giving feedback etc moving forward.

**Closed by iambmelt** 2019-01-09 18:11 UTC
Labels: Duplicate
