### ISSUE TITLE
No Activity found to handle AuthenticationActivity in msal library

### ISSUE THREAD

**Issue by NavalKishor** [AzureAD/microsoft-authentication-library-for-android#237] opened 2017-12-01 10:09 UTC
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.naval.libs/com.microsoft.identity.client.AuthenticationActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://www.xxxxlogin.com/... pkg=com.android.chrome launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } }
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3873)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3914)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3070)
at android.app.ActivityThread.-wrap14(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6823)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

Caused by android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://www.xxxxxlogin.com/... pkg=com.android.chrome launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1844)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1531)
at android.app.Activity.startActivityForResult(Activity.java:4411)
at android.app.Activity.startActivityForResult(Activity.java:4369)
at android.app.Activity.startActivity(Activity.java:4708)
at android.app.Activity.startActivity(Activity.java:4676)
at com.microsoft.identity.client.AuthenticationActivity.onResume(SourceFile:237)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
at android.app.Activity.performResume(Activity.java:7140)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3850)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3914)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3070)
at android.app.ActivityThread.-wrap14(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6823)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

In AndroidManifest.xml

Device Details

Platform: android

Date: 2017-11-23T06:34:00Z

OS Version: 7.1.1

Device: SM-N950U

RAM Free: 14.6%

Disk Free: 78.6%

**Comment by doug-l-mitchell** [comment] 2018-02-06 01:18
I have reports of the same problem only with 
Samsung Galaxy S7 Edge (hero2qlteatt), 4096MB RAM, Android 7.0
and
Samsung Galaxy S8 (dreamqltesq), 4096MB RAM, Android 7.0


java.lang.RuntimeException: 
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3832)
  at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3872)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3014)
  at android.app.ActivityThread.-wrap14 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1650)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6688)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1468)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1358)
Caused by: android.content.ActivityNotFoundException: 
  at android.app.Instrumentation.checkStartActivityResult (Instrumentation.java:1839)
  at android.app.Instrumentation.execStartActivity (Instrumentation.java:1531)
  at android.app.Activity.startActivityForResult (Activity.java:4389)
  at android.app.Activity.startActivityForResult (Activity.java:4348)
  at android.app.Activity.startActivity (Activity.java:4672)
  at android.app.Activity.startActivity (Activity.java:4640)
  at com.microsoft.identity.client.AuthenticationActivity.onResume (AuthenticationActivity.java:237)
  at android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1277)
  at android.app.Activity.performResume (Activity.java:7058)
  at android.app.ActivityThread.performResumeActivity (ActivityThread.java:3809)

**Comment by blacktea** [comment] 2018-03-07 16:27
You must have Chrome installed. MSAL requires chrome (in the current iteration)

**Comment by NavalKishor** [comment] 2018-03-08 12:19
Hi AzureAD team, This error is occurring only after user had invoked the login page in Chrome through her the app and enter the user ID and password and clicked on login... 
Sent from Yahoo Mail on Android 
 
  On Wed, 7 Mar 2018 at 9:57 PM, blacktea<notifications@github.com> wrote:   
You must have Chrome installed. MSArequires chrome (in the current iteration)

**Comment by iambmelt** [comment] 2019-09-30 22:36
Closing as old/invalid -- please reopen if the `1.0.0` release exhibits issues

**Closed by iambmelt** 2019-09-30 22:36 UTC
Labels: Bug, P1
