### ISSUE TITLE
Service not registered issue when using the don't keep activities flag

### ISSUE THREAD

**Issue by 4gus71n** [AzureAD/microsoft-authentication-library-for-android#454] opened 2018-11-11 19:40 UTC
Hi,

I'm having some issues when setting the "Don't keep activities" flag to true. Everything works just fine if I disable the flag. 

I'm using the `microsoftMsalIdentityClient : 'com.microsoft.identity.client:msal:0.2.1'` version and I'm injecting the `PublicClientApplication` through Dagger:

```
    @Provides
    @Singleton
    fun providePublicClientApplication(context: Context): PublicClientApplication {
        return PublicClientApplication(
            context,
            IDaaSConfiguration.CLIENT_ID,
            String.format(
                IDaaSConfiguration.AUTHORITY,
                IDaaSConfiguration.TENANT, IDaaSConfiguration.SISU_POLICY)
        )
    }
``` 

This is my stacktrace:

```
    Process: com.sarasa.sarasa, PID: 19916
    java.lang.RuntimeException: Unable to resume activity {com.sarasa.sarasa/com.sarasa.sarasa.iris.ui.login.LoginActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=2003, data=Intent { (has extras) }} to activity {com.sarasa.sarasa/com.sarasa.sarasa.iris.ui.login.LoginActivity}: java.lang.IllegalArgumentException: Service not registered: com.microsoft.identity.common.internal.ui.browser.CustomTabsManager$1@2b9e2ff
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4221)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4323)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3426)
        at android.app.ActivityThread.access$1100(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7325)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=2003, data=Intent { (has extras) }} to activity {com.sarasa.sarasa/com.sarasa.sarasa.iris.ui.login.LoginActivity}: java.lang.IllegalArgumentException: Service not registered: com.microsoft.identity.common.internal.ui.browser.CustomTabsManager$1@2b9e2ff
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4998)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4207)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4323) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3426) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:7325) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
     Caused by: java.lang.IllegalArgumentException: Service not registered: com.microsoft.identity.common.internal.ui.browser.CustomTabsManager$1@2b9e2ff
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1160)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1475)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:644)
        at com.microsoft.identity.common.internal.ui.browser.CustomTabsManager.unbind(CustomTabsManager.java:138)
        at com.microsoft.identity.common.internal.ui.browser.BrowserAuthorizationStrategy.dispose(BrowserAuthorizationStrategy.java:132)
        at com.microsoft.identity.common.internal.ui.browser.BrowserAuthorizationStrategy.completeAuthorization(BrowserAuthorizationStrategy.java:114)
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.completeAcquireToken(LocalMSALController.java:235)
        at com.microsoft.identity.client.internal.controllers.MSALInteractiveTokenCommand.notify(MSALInteractiveTokenCommand.java:68)
        at com.microsoft.identity.client.internal.controllers.MSALApiDispatcher.completeInteractive(MSALApiDispatcher.java:244)
        at com.microsoft.identity.client.PublicClientApplication.handleInteractiveRequestRedirect(PublicClientApplication.java:412)
        at com.sarasa.sarasa.iris.ui.login.presenter.LoginPresenterImpl.handleInteractiveRequestRedirect(LoginPresenterImpl.kt:71)
        at com.sarasa.sarasa.iris.ui.login.LoginActivity.onActivityResult(LoginActivity.kt:145)
        at android.app.Activity.dispatchActivityResult(Activity.java:7165)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4994)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4207) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4323) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3426) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:7325) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
```

Any ideas why this could be happening? It's a known issue?

**Comment by 4gus71n** [comment] 2018-11-11 20:01
**Update:**

I tried to remove the dependency injection, and just use the PublicClientApplication instance in the Activity and the same error popped up

**Comment by shoatman** [comment] 2018-11-12 16:45
"Don't keep activities" is a dev option to assist in testing.  Is that how you are using it?  In MSAL device browsers are used by default when authorizing a request.  I'm guessing that the browser is being killed as a result of this setting in way that MSAL is not currently handling correctly.  Marking with the investigate tag.

**Comment by 4gus71n** [comment] 2018-11-12 17:08
Thanks for taking a look @shoatman 

I'm using the "Don't keep activities" to make sure that all the properties used across the different screens are being properly saved into the onSaveInstance bundle. Testing this implies testing from the login screen all the way through the last screen.

I could successfully tested the App by disabling the flag during the login and enabling it once I'm logged in. However, I'm worried that a user with a really low-spec device is going to run into this issues. Worst of all, is that this issue prevents the user from login in.

All the feedback that I can give you is:

- I tried changing the library's version from 0.2.1 to 0.2.0 and below
- I'm using dependency injection with dagger to provide the PublicClientApplication instance. I tried removing all this and declaring the PublicClientApplication directly in the Activity.

One thing that sounds a little bit off is that says `java.lang.IllegalArgumentException: Service not registered: com.microsoft.identity.common.internal.ui.browser.CustomTabsManager$1@2b9e2ff` like if it's kinda leaking a service, could be that the PublicClientApplication client uses some kind of IntentService/Service that is not being registered again when the LoginActivity gets re-created?

Let me know if I can help you with something else.

Thanks again for your time.

**Comment by MoBo** [comment] 2018-11-14 13:16
I am experiencing the same crash. In version 0.1.3 this issue didn't exits.

**Comment by 4gus71n** [comment] 2018-11-17 12:08
@MoBo  Sorry, but are you positive that this is working with the `0.1.3` version with the "Don't keep activities flag"? I've to go to production in a couple of weeks and I cannot have this bug lingering around.

**Comment by iambmelt** [comment] 2019-12-11 18:35
Dupe of https://github.com/AzureAD/microsoft-authentication-library-common-for-android/issues/353

Closing to track there

**Closed by iambmelt** 2019-12-11 18:35 UTC
Labels: Investigate
