### ISSUE TITLE
NullPointerException: libcore.reflect.TypeVariableImpl.hashCode TypeVariableImpl.java, line 47 java.lang.

### ISSUE THREAD

**Issue by azakharenka1** [AzureAD/microsoft-authentication-library-for-android#1209] opened 2020-11-09 08:03 UTC
**Crash from app center**
Production 

**Smartphone (please complete the following information):**
 - HUAWEI P30 lite
 - Android Version: 10
 - Browser web view
 - MSAL Version 1.6.0

**Stacktrace**
libcore.reflect.TypeVariableImpl.hashCode TypeVariableImpl.java:47
java.util.HashMap.hash HashMap.java:347
java.util.HashMap.containsKey HashMap.java:607
java.util.HashSet.contains HashSet.java:203
com.google.gson.internal.$Gson$Types.resolve .java:346
com.google.gson.internal.$Gson$Types.resolve .java:381
com.google.gson.internal.$Gson$Types.resolve .java:337
com.google.gson.internal.$Gson$Types.getSupertype .java:283
com.google.gson.internal.$Gson$Types.getCollectionElementType .java:302
com.google.gson.internal.bind.CollectionTypeAdapterFactory.create CollectionTypeAdapterFactory.java:52
com.google.gson.Gson.getAdapter Gson.java:458
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField ReflectiveTypeAdapterFactory.java:117
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields ReflectiveTypeAdapterFactory.java:166
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create ReflectiveTypeAdapterFactory.java:102
com.google.gson.Gson.getAdapter Gson.java:458
com.google.gson.internal.bind.CollectionTypeAdapterFactory.create CollectionTypeAdapterFactory.java:53
com.google.gson.Gson.getAdapter Gson.java:458
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField ReflectiveTypeAdapterFactory.java:117
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields ReflectiveTypeAdapterFactory.java:166
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create ReflectiveTypeAdapterFactory.java:102
com.google.gson.Gson.getAdapter Gson.java:458
com.google.gson.Gson.fromJson Gson.java:931
com.google.gson.Gson.fromJson Gson.java:897
com.google.gson.Gson.fromJson Gson.java:846
com.google.gson.Gson.fromJson Gson.java:817
com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.loadConfiguration PublicClientApplicationConfigurationFactory.java:165
com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.loadConfiguration PublicClientApplicationConfigurationFactory.java:117
com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.initializeConfiguration PublicClientApplicationConfigurationFactory.java:69
com.microsoft.identity.client.PublicClientApplication$6.run PublicClientApplication.java:625
java.lang.Thread.run Thread.java:929

**Comment by AdamBJohnsonx** [comment] 2020-11-12 19:42
Is there any way you could provide us with the configuration that resulted in this exception?

**Comment by azakharenka1** [comment] 2020-11-13 08:07
{
  "client_id": "***",
  "authorization_user_agent": "WEBVIEW",
  "redirect_uri": "msauth://***.mobile.debug/EH9x23KWn0w8lSiTahV6Q%2F%2FH95",
  "broker_redirect_uri_registered": true,
  "shared_device_mode_supported": false,
  "account_mode": "SINGLE",
  "authorities": [
    {
      "type": "B2C",
      "authority_url": "https://***.b2clogin.com/tfp/***.onmicrosoft.com/B2C_1A_Signup_Signin_With_Kmsi",
      "default": true
    }
  ]
}

**Comment by azakharenka1** [comment] 2020-11-20 08:36
@AdamBJohnsonx any progress with it ?

**Comment by AdamBJohnsonx** [comment] 2020-12-01 22:03
https://github.com/google/gson/issues/1778 This looks like a similar issue. As a question, are you running proguard?

**Comment by AdamBJohnsonx** [comment] 2021-01-15 17:23
https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1277

**Comment by AdamBJohnsonx** [comment] 2021-01-19 17:16
I have not been able to reproduce this issue: is it happening with the latest MSAL?

**Comment by AdamBJohnsonx** [comment] 2021-01-26 19:12
Resolving issue due to lack of reproduction.

**Closed by AdamBJohnsonx** 2021-01-26 19:12 UTC
Labels: Issue Triage, More Info
