### ISSUE TITLE
[LocalMSALControler is not eligible to use the broker]

### ISSUE THREAD

**Issue by thangld8** [AzureAD/microsoft-authentication-library-for-android#869] opened 2019-12-17 08:54 UTC
**Describe the bug**
From LoginActivity, After I get Account so I try to pass IAccount as a Params to my JobServices:
```java
   b2cApp.getAccounts(new IPublicClientApplication.LoadAccountsCallback() {
            @Override
            public void onTaskCompleted(final List<IAccount> result) {
                // parse IAccount to String
                result.get(0);
                Gson gson = new Gson();
                String resultJson = gson.toJson(result.get(0));
                // Save IAccount to Preference
                EncryptPreference preference = EncryptPreference.getInstance(getContext());
                preference.setB2cAccountInfo(resultJson);

                // create PersistableBundle and JobInfo
                PersistableBundle bundle = new PersistableBundle();
                bundle.putString("listAccount", resultJson);
                b2CUsers = B2CUser.getB2CUsersFromAccountList(result);
                ComponentName refreshAccessTokenService = new ComponentName(getContext(), MerchantRefreshAccessTokenServices.class);
                JobInfo jobInfoRefreshToken = new JobInfo.Builder(1, refreshAccessTokenService)
                        .setPeriodic(5000)
                        .setExtras(bundle)
                        .setPersisted(true)
                        .build();

                JobScheduler jobScheduler = (JobScheduler)getSystemService(JOB_SCHEDULER_SERVICE);
                int resultCode = jobScheduler.schedule(jobInfoRefreshToken);
                if (resultCode == JobScheduler.RESULT_SUCCESS) {
                    Log.d(TAG, "Job scheduled!");
                } else {
                    Log.d(TAG, "Job not scheduled");
                }
            }

            @Override
            public void onError(MsalException exception) {
                displayError(exception);
            }
        });
```
After that, I am trying to call acquireTokenSilentAsync from JobService of Android:
```java
String resultJson = jobParameters.getExtras().getString("listAccount");
            try {
                Gson gson = new Gson();
                IAccount iAccount = gson.fromJson(resultJson, IAccount.class);
                AcquireTokenSilentParameters parameters = new AcquireTokenSilentParameters.Builder()
                        .fromAuthority(B2CConfiguration.getAuthorityFromPolicyName(Constants.B2C_SINGIN_POLICY[0]))
                        .withScopes(B2CConfiguration.getScopes())
                        .forAccount(iAccount)
                        .withCallback(getAuthSilentCallback())
                        .build();

                b2cApp.acquireTokenSilentAsync(parameters);
            } catch (Exception e) {
                LogManager.LogE(e.getMessage());
            }
```
But when The Job was started, it returns:
 
```java
E/LocalMSALController:getDeviceMode:  [2019-12-17 07:55:53 - {"thread_id":"1507","correlation_id":"1141af56-98ed-44fa-9be6-edbedf8fd13a"}] LocalMSALControler is not eligible to use the broker. Do not check sharedDevice mode and return false immediately. Android 28
W/Telemetry:  [2019-12-17 07:55:53 - {"thread_id":"2","correlation_id":"dd03d427-41db-431c-a9b8-9bceca7afcef"}] Telemetry is disabled because the Telemetry context or configuration is null Android 28
```

**Comment by iambmelt** [comment] 2019-12-18 21:59
Assigning to @rpdome 

@thangld8 Are you experiencing any issues? Or just following up on what this message means? AFAIK, this message isn't indicative of a problem; @rpdome to follow-up

**Comment by iambmelt** [comment] 2019-12-18 22:00
@rpdome I am going to file an issue to lower the `LOG_LEVEL` of this message to `warning`

**Comment by thangld8** [comment] 2019-12-19 05:25
@iambmelt Thanks for replying me,

I am facing the issue:

Fast brief:
+ I am trying to call `acquireTokenSilentAsync` to refresh my token in JobService of Android.

But when I create new `IMultipleAccountPublicClientApplication` in JobService and try to get IAccount by:

`
IAccount iAccount = null;

        if (b2cApp != null) {
            String iAccountId = jobParameters.getExtras().getString("iAccountId");
            try {
                List<String> scopes = Arrays.asList(
                        "https://krispaydev.onmicrosoft.com/api/read",
                        "https://krispaydev.onmicrosoft.com/api/write",
                        "https://krispaydev.onmicrosoft.com/api/user_impersonation"
                );
                iAccount = b2cApp.getAccount(iAccountId);

                AcquireTokenSilentParameters parameters = new AcquireTokenSilentParameters.Builder()
                        .fromAuthority(B2CConfiguration.getAuthorityFromPolicyName(Constants.B2C_SINGIN_POLICY[0]))
                        .withScopes(B2CConfiguration.getScopes())
                        .forAccount(iAccount)
                        .withCallback(getAuthSilentCallback())
                        .build();
                    b2cApp.acquireTokenSilentAsync(parameters);
            } catch (Exception e) {
                LogManager.LogE(e.getMessage());
            }

        }
`

But it's returning above error message and I cannot refresh my token

**Comment by thangld8** [comment] 2019-12-19 05:27
@iambmelt  Thanks for replying me,

I am facing the issue:

Fast brief:

I am trying to call acquireTokenSilentAsync to refresh my token in JobService of Android.
But when I create new IMultipleAccountPublicClientApplication in JobService and try to get IAccount by:

`
IAccount iAccount = null;

    if (b2cApp != null) {
        String iAccountId = jobParameters.getExtras().getString("iAccountId");
        try {
            iAccount = b2cApp.getAccount(iAccountId);

            AcquireTokenSilentParameters parameters = new AcquireTokenSilentParameters.Builder()
                    .fromAuthority(B2CConfiguration.getAuthorityFromPolicyName(Constants.B2C_SINGIN_POLICY[0]))
                    .withScopes(B2CConfiguration.getScopes())
                    .forAccount(iAccount)
                    .withCallback(getAuthSilentCallback())
                    .build();
                b2cApp.acquireTokenSilentAsync(parameters);
        } catch (Exception e) {
            LogManager.LogE(e.getMessage());
        }

    }
`

But it's returning above error message and I cannot refresh my token

**Comment by iambmelt** [comment] 2019-12-19 18:02
@thangld8 I would say that this error message is a red herring -- are you receiving an `Exception` in your `AuthenticationResult`'s `onError()` callback?

Additionally, it looks like you're doing background work - have your seen our [synchronous method for `acquireTokenSilent()`](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/IPublicClientApplication.java#L77-L85)? Depending on your implementation, this may provide a simpler API for your use case

Also, you may want to bump up the logging verbosity of MSAL - information on tweaking loglevels/outputs is available [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=android#logging-in-msal-for-android-using-java).

**Comment by thangld8** [comment] 2019-12-20 03:39
@iambmelt  Thanks for your information.

- I am not having the above error message in AuthenticationResult's onError() callback? and also don't know where is this, it appears when my background services running.

- I am confusing between 2 methods acquireTokenSilentAsync and acquireTokenSilent, is that the same? Or how can I get a refresh token to manually call API?

**Comment by rpdome** [comment] 2019-12-23 16:52
Hi @thangld8,

- You saw this particular error message because we logged it with a wrong type (error). We do not throw any exception and It should not affect the functionality of B2C MSAL in any way. Are you running into any issue here?

- AcquireTokenSilent is a blocking/synchronous version (no callback required) of AcquireToken. It can be invoked in a background thread only. Their functionalities are the same.

**Comment by thangld8** [comment] 2019-12-24 02:32
@rpdome I have trouble when running `IMultipleAccountPublicClientApplication` in JobService. I am trying to get a new token every hour by:

`
b2cApp.getAccount(iAccountId, new IMultipleAccountPublicClientApplication.GetAccountCallback() {

                @Override
                public void onTaskCompleted(IAccount result) {
                    Log.d(TAG, "iAccountId" + result);
                    AcquireTokenSilentParameters parameters = new AcquireTokenSilentParameters.Builder()
                            .fromAuthority(B2CConfiguration.getAuthorityFromPolicyName(Constants.B2C_SINGIN_POLICY[0]))
                            .withScopes(B2CConfiguration.getScopes())
                            .forAccount(result)
                            .forceRefresh(true)
                            .withCallback(new SilentAuthenticationCallback() {

                                @Override
                                public void onSuccess(IAuthenticationResult authenticationResult) {
                                    Log.d(TAG, "Successfully authenticated " + authenticationResult.getExpiresOn().toGMTString());
                                    Log.d(TAG, "Successfully authenticated Token: " + authenticationResult.getAccessToken());
                                    saveAuthenInfo(authenticationResult);
                                    /* Successfully got a token. */
                                }

                                @Override
                                public void onError(MsalException exception) {
                                    /* Failed to acquireToken */
                                    Log.e(TAG, "Authentication failed1: " + exception.toString());

                                    if (exception instanceof MsalClientException) {
                                        /* Exception inside MSAL, more info inside MsalError.java */
                                        Log.e(TAG, "Authentication failed2: " + exception.toString());
                                    } else if (exception instanceof MsalServiceException) {
                                        /* Exception when communicating with the STS, likely config issue */
                                        Log.e(TAG, "Authentication failed3: " + exception.toString());
                                    } else if (exception instanceof MsalUiRequiredException) {
                                        /* Tokens expired or no session, retry with interactive */
                                        Log.e(TAG, "Authentication failed4: " + exception.toString());
                                    }
                                }
                            })
                            .build();
                    b2cApp.acquireTokenSilentAsync(parameters);
`

But sometimes It can return new Token, but almost the times I haven't seen the running.
Is that stable when I created a new `IMultipleAccountPublicClientApplication` in JobService and run as scheduled?

**Comment by rpdome** [comment] 2019-12-30 13:22
@thangld8 May I ask which one of the following statement is true?
1. You noticed that JobService is running as intended. acquireTokenSilent was initiated every X hour but sometimes didn't finish the operation.
or 
2. JobService is not running consistently. Sometimes, acquireTokenSilent was initiated and sometimes it was not.

I suspect that this could be because [the device is in doze mode].(https://developer.android.com/training/monitoring-device-state/doze-standby#restrictions).

**Closed** 2020-01-16 05:56 UTC
Labels: Issue Triage, More Info, Question
