### ISSUE TITLE
onCancel callback not called when Browser is used

### ISSUE THREAD

**Issue by azakharenka1** [AzureAD/microsoft-authentication-library-for-android#963] opened 2020-03-05 08:19 UTC
In our app we have 3 different applications with separate authorities for login/forgot password/
registration. After clicking forgot password link from login page in chrome tab we are getting **com.microsoft.identity.client.exception.MsalServiceException: access_denied;AADB2C90118: The user has forgotten their password** error and opening another application (forgot password) as described here - https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-android-b2c#handle-password-change-policies 
The problem happens on the latest versions of msal for android, starting from **1.2.0** after pressing back button on forgot password page -> we are still getting  **AADB2C90118** error instead of **onCancel** (happens on 1.1.0-hf1). But it's not the main thing. After opening login application again and pressing back button after it will load, instead of onCancel we are still getting **AADB2C90118** error and according to our logic, opening forgot password app =(. 

**Smartphone:**
 - Device: Pixel 3XL, OnePlus 3T
 - Android Version: 28, 29
 - Browser Chrome Tabs
 - MSAL Version 1.2.0, 1.3.0, 1.4.0

**Stacktrace**
From 1.4.0: https://raw.githubusercontent.com/azakharenka1/msal_logs/master/1.4.0.txt
From 1.2.0 https://raw.githubusercontent.com/azakharenka1/msal_logs/master/1.2.0.txt
From 1.1.0-hf1 - **NO issue** https://raw.githubusercontent.com/azakharenka1/msal_logs/master/1.1.0-hf1.txt

**To Reproduce**
1.  Open login 
2. Click on forgot password link - got AADB2C90118 error (expected)
3. App will open forgot password screen
4. Click back button
4. See AADB2C90118 error (not sure if expected, in 1.1.0-hf1 version we got onCanceled callback)
5. Open login, wait for load
6. Click back button
7. See AADB2C90118 error

**Expected behavior**
No 2nd and 3rd AADB2C90118 error for login application, onCanceled callback triggered as usual

**Actual Behavior**
On the latest msal versions 1.2.0, 1.3.0, 1.4.0 : AADB2C90118 error in login app after going back from it

**Additional context**
Does not reproduce on version <= 1.1.0-hf1

**Comment by azakharenka1** [comment] 2020-03-17 08:35
Any updates here?

**Comment by shahzaibj** [comment] 2020-03-20 18:21
@azakharenka1 Thanks for reporting. I've identified the issue and will open a PR with a fix soon.

**Comment by shahzaibj** [comment] 2020-03-20 18:25
The issue is happening as we are still holding a reference to the server response from the previous authorization request. See [this file](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/f789cd6ae92da4c704c440bf4ff43fe9036cb275/common/src/main/java/com/microsoft/identity/common/internal/providers/oauth2/BrowserAuthorizationFragment.java#L167).

So when the user cancels, we hit either onError or onSuccess depending on the result of the previous authorization request.

**Comment by shahzaibj** [comment] 2020-03-20 18:31
@azakharenka1 I've opened up a PR to fix it here: https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/867

The fix will be included in the next release of MSAL

**Closed** 2020-03-20 21:49 UTC
Labels: Bug - P2, Issue Triage
