### ISSUE TITLE
Nullpointer on AuthorizationFragment

### ISSUE THREAD

**Issue by xyzwilliamxyz** [AzureAD/microsoft-authentication-library-for-android#1093] opened 2020-07-13 14:42 UTC
**Describe the bug**
We have moved our app to production and after one week we started getting this internal crash from msal that currently has 500+ ocurrencies. I'm not sure how to reproduce it, but msal team may have an idea by the stack trace. Could you please check on this?

**Smartphone (please complete the following information):**
 - Device: Multiple devices
 - Android Version: 6, 8, 9, 10
 - MSAL Version: 1.5.1

**Stacktrace**
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.fragment.app.FragmentTransaction androidx.fragment.app.FragmentManager.beginTransaction()' on a null object reference
       at com.microsoft.identity.common.internal.providers.oauth2.AuthorizationFragment.finish(AuthorizationFragment.java:117)
       at com.microsoft.identity.common.internal.providers.oauth2.WebViewAuthorizationFragment$AuthorizationCompletionCallback.onChallengeResponseReceived(WebViewAuthorizationFragment.java:242)
       at com.microsoft.identity.common.internal.ui.webview.AzureActiveDirectoryWebViewClient.processRedirectUrl(AzureActiveDirectoryWebViewClient.java:205)
       at com.microsoft.identity.common.internal.ui.webview.AzureActiveDirectoryWebViewClient.handleUrl(AzureActiveDirectoryWebViewClient.java:137)
       at com.microsoft.identity.common.internal.ui.webview.AzureActiveDirectoryWebViewClient.shouldOverrideUrlLoading(AzureActiveDirectoryWebViewClient.java:99)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:17)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:330)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5659)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)`

**Additional context**
We got his from crashlytics.

Thanks!

**Comment by iambmelt** [comment] 2020-07-13 18:22
Dupe of #1072 see [guidance](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1072#issuecomment-648998861)

Fixed by:
https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/926

Closing, as this issue is known, fixed

/cc @rpdome

**Closed by iambmelt** 2020-07-13 18:22 UTC
Labels: Issue Triage

**Comment by iambmelt** [comment] 2020-07-13 18:23
Please follow-up or reopen issues if you continue to experience issues after upgrading to the latest version
