### ISSUE TITLE
Library fails for B2C login when no Access Token is returned

### ISSUE THREAD

**Issue by ugurcany** [AzureAD/microsoft-authentication-library-for-android#563] opened 2019-04-05 21:39 UTC
Using `msal:0.2.2`

After successfully logged in using B2C method, getting the following exception therefore failure at auth callback:

```
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
      at com.microsoft.identity.common.internal.cache.MicrosoftStsAccountCredentialAdapter.getExpiresOn(MicrosoftStsAccountCredentialAdapter.java:231)
      at com.microsoft.identity.common.internal.cache.MicrosoftStsAccountCredentialAdapter.createAccessToken(MicrosoftStsAccountCredentialAdapter.java:78)
      at com.microsoft.identity.common.internal.cache.MicrosoftStsAccountCredentialAdapter.createAccessToken(MicrosoftStsAccountCredentialAdapter.java:45)
      at com.microsoft.identity.common.internal.cache.MsalOAuth2TokenCache.save(MsalOAuth2TokenCache.java:112)
      ...
```

And here is my raw config file:
```
{
  "client_id" : "XXX",
  "authorization_user_agent" : "DEFAULT",
  "redirect_uri" : "msalXXX://auth",
  "authorities" : [
    {
      "type": "B2C",
      "authority_url": "https://TTT.b2clogin.com/tfp/TTT.onmicrosoft.com/B2C_1_susi/"
    }
  ]
}
```
where XXX is client id, and TTT is tenant.

It seems like the field "expires_in" in token response happens to be null, so auth fails inside the library although we get successful response from browser.

**Comment by heidijinxujia** [comment] 2019-04-09 21:27
Hi @ugurcany Do you have a test account where we could repo this issue? It is unexpected to get a null "expired_in" from the token response.

**Comment by ugurcany** [comment] 2019-04-09 21:29
Unfortunately, I cannot provide test account. However, I also posted this issue on SO, and you can find the library log there. Please check the link: https://stackoverflow.com/questions/55576359/msal-for-android-fails-performing-b2c-login

**Comment by heidijinxujia** [comment] 2019-04-09 21:38
Does it happen to all the users under this tenant? or just one account?

Are you using fb, google, twitter or msa account?

**Comment by ugurcany** [comment] 2019-04-09 21:42
It happens for all users under this tenant. I use my sign up & sign in flow. So, first I sign up using my outlook or work email (doesn't matter), then I try to sign in with it. Btw, the browser step does its job correctly, because when I put debug point before createAccessToken method called (inside library), I can observe successful jwt token with all correct info in it. However, the library has issue with decoding it I guess.

**Comment by ugurcany** [comment] 2019-04-18 10:50
@heidijinxujia is there any update on this issue?

**Comment by iambmelt** [comment] 2019-04-22 17:26
Hi @ugurcany From investigation on our side, this is looking like a policy setting where tokens can be returned _either_ as a String or an integer -- MSAL today, assumes this value is [_always_ numeric](https://openid.net/specs/openid-connect-core-1_0.html#JSONSerialization) - we're working to provide a remediation or workaround soon.

**Comment by iambmelt** [comment] 2019-04-24 20:26
B2C may return the token response’s expires_in in either a numeric or String format, depending on the configuration of the policy. MSAL’s current implementation assumes this value is always numeric per OIDC & AAD’s documentation.
 
MSAL currently cannot parse this field when it’s not numeric and so the token acquisition fails.
 
This is a policy setting which can be tweaked – until a more permanent solution is in place, our guidance is to configure the policy thusly – it should be the default behavior for new registrations.
 
```xml
<TechnicalProfile Id="JwtIssuer">
    <DisplayName>JWT Issuer</DisplayName>
    <Protocol Name="None" />
    <OutputTokenFormat>JWT</OutputTokenFormat>
    <Metadata>
        <Item Key="client_id">{service:te}</Item>
        <Item Key="issuer_refresh_token_user_identity_claim_type">objectId</Item>
        <Item Key="SendTokenResponseBodyWithJsonNumbers">true</Item> <!-- Toggle numeric output -->
    </Metadata>
```

**Comment by bahtiyarkaba** [comment] 2019-04-26 05:30
Hi @iambmelt 
I am working with ugurcan on this issue. Thank you for your answers. 
We are using the existing Sign in Sign Up policy.  Does your suggestion mean creating a custom one via the Identity Experience Framework (we don't know much about it) or do we have a way of customizing the policy? 
Also, I suspect the issue will be resolved with this. When I decode the token I don't see a "expires_in" field, but only "exp" which is already numeric, yet I understand MSAL is waiting an expires_in field.

**Comment by iambmelt** [comment] 2019-04-26 17:22
@bahtiyarkaba The `expires_in` should be present in the JSON of the `/token` response...

In AAD, these responses look like this:
```json
{
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik5HVEZ2ZEstZnl0aEV1Q...",
    "token_type": "Bearer",
    "expires_in": 3599,
    "scope": "https%3A%2F%2Fgraph.microsoft.com%2Fuser.read",
    "refresh_token": "AwABAAAAvPM1KaPlrEqdFSBzjqfTGAMxZGUTdM0t4B4...",
    "id_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIyZDRkMTFhMi1mODE0LTQ2YTctOD...",
}
```

Whereas in B2C for policies configured with `SendTokenResponseBodyWithJsonNumbers == false`, the following kind of response would be returned:

```json
{
    "not_before": "1442340812",
    "token_type": "Bearer",
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik5HVEZ2ZEstZnl0aEV1Q...",
    "scope": "90c0fe63-bcf2-44d5-8fb7-b8bbc0b29dc6 offline_access",
    "expires_in": "3600",
    "refresh_token": "AAQfQmvuDy8WtUv-sd0TBwWVQs1rC-Lfxa_NDkLqpg50Cxp5Dxj0VPF1mx2Z...",
}
```

And this difference in data-type of the `expires_in` is causing the issue.

As for configuring the policy... at some point, a [SUSI policy would have been created](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows#create-a-sign-up-and-sign-in-user-flow) - it's possible there may be some means of configuring the finer aspects of this policy within the portal - probably within 'Properties' if I had to guess, though admittedly my familiarity with this part of the portal is minimal.

![azure-portal-flow-edit-screenshot-768x671](https://user-images.githubusercontent.com/990063/56824586-bc06c500-680b-11e9-85ee-c847f91cb952.jpg)
(image credit: thirdspace)

If you're using custom policies already, the above guidance around around modifying the policy should apply - there's documentation around this [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-manage-sso-and-token-configuration).

For more information on B2C policy config, StackOverflow might be a great next-stop. If you do file a question on this, feel free to ping me and link back here and I can try to pair you up with a SME

**Comment by ugurcany** [comment] 2019-05-10 15:59
@iambmelt it's not possible to update configuration (that you suggested) of SUSI policy through portal. there is no such page in the dashboard to achieve that.

btw, we already filed a question on this on SO: https://stackoverflow.com/questions/55576359/msal-for-android-fails-performing-b2c-login

**Comment by iambmelt** [comment] 2019-05-10 20:24
@ugurcany Thanks for posting this question. I have reached out to the B2C dev team to see if someone can lend some guidance on policies.

**Comment by Larrsenn** [comment] 2019-06-13 13:04
@iambmelt  any news on this issue? Kind of blocking not being able to log in due to this. :)

**Comment by iambmelt** [comment] 2019-06-13 16:35
@Larrsenn The current guidance is to configure a custom SISU (sign-in, sign-up) policy through the Identity Experience Framework and apply [these policy settings](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/563#issuecomment-486412036).

For more information on configuring custom policies, see [these docs](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-overview-custom).

**Comment by Larrsenn** [comment] 2019-06-14 07:00
@iambmelt will have a look at it - thank you. Are there any estimation on fixing the issue rather than doing a work around?

**Comment by Larrsenn** [comment] 2019-06-14 10:13
@iambmelt Hello again.
So we've tried updating the policies with this workaround you gave me. Sadly, when trying to debug all the way down into the LocalMSALController.java, I can see this line:

            final TokenResult tokenResult = performTokenRequest(oAuth2Strategy, mAuthorizationRequest, result.getAuthorizationResponse(), parameters);

is giving me a tokenResult that looks like this(in the tokenResponse):

MicrosoftTokenResponse{
mExtExpiresOn=null, 
mClientInfo='STRING_IS_HERE', 
mClientId='null',
mExtendedExpiresIn=null, 
mFamilyId='null'} 
TokenResponse{
mExpiresIn=null, 
mAccessToken='null', 
mTokenType='Bearer', mRefreshToken='ACCESS_TOKEN',
mScope='', 
mState='null', mIdToken='ACCESS_TOKEN',
mResponseReceivedTime=0}

Hopefully, you can point me in some direction here. :)

**Comment by josephbnb** [comment] 2019-07-15 12:13
@Larrsenn I tried your suggestion and I was able to get an access token ( `val SCOPES = arrayOf("CLIENT_ID")` ).
However the tokens I'm getting do not authorize the api i'm trying to access since the requested scope is different. Did you have the same issue? @iambmelt do you have any input on this?

**Comment by JanLoehr** [comment] 2019-08-07 19:46
Sorry for bumping this topic. But is there a fix planned for this? As this is still present as well in the current released as in the latest pre-release version :( The work-around seems pretty time consuming.

**Comment by iambmelt** [comment] 2019-08-07 19:49
@JanLoehr There isn't presently a fix in the works for this on the client-side. I have heard murmurs that the B2C Portal _may_ provided an in-portal toggle for this.

More on this as I have details; if this remains a long-term pain we'll find a better client-side mitigation

**Comment by iambmelt** [comment] 2019-08-07 19:51
@josephbnb Multiple scopes can be included in your request, have you tried this? Sample code could help explain your specific issue

**Comment by josephbnb** [comment] 2019-08-08 09:13
@iambmelt @JanLoehr I was able to fix the issue, it was a configuration error in Azure on my side. I was using the same B2C application for both backend and android. I created a new application specifically for Android and gave it API access to the backend B2C application (which contains the scopes).

Some comments though:
- I investigated the code a bit and I think the core of the issue is that instead of throwing an exception indicating that there is a misconfiguration, the library receives a null token in the response which then causes an internal `NullPointerException` when attempting to access any field inside the token class. I also downgraded to previous versions and got the same issue.
- The documentation on how to configure the B2C portal is really poor, I figured out the solution after stumbling upon an article on medium, written by someone who wasn't even using Android.
- Multiple scopes do not work. When I tried them I got an error that says they aren't supported yet.

**Comment by iambmelt** [comment] 2019-08-08 16:58
Thanks for the feedback @josephbnb - I'll take this as a TODO around some more helpful messaging when these errors are encountered.

As for the documentation that unblocked you; please do feel free to link that blog post here so that it may help others.

As for multiple scopes, this isn't strictly true AFAIK - each request will include 3 "base scopes" of `openid`, `profile`, and `offline_access` (MSAL does this for you automatically) and may contain [additional scopes](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens#scopes) needed for the [User Flow](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-policies). 

As far as constraints are concerned around _which_ scopes can be sent, scopes spanning _multiple policies_ are not supported today, but for a (1) policy, multiple scopes should be configurable: for instance, you might configure a policy to limit access to an address book, and the policy might accept such scopes as `addressbook.read`, `addressbook.write` - curious to hear if this is inconsistent with your dev experience.

**Comment by nickplennox** [comment] 2019-11-21 14:21
I am getting exactly the same error `Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference` following a successful interactive login, and I already have the recommended config for JwtIssuer in my custom policy config

`
        <TechnicalProfile Id="JwtIssuer">
          <DisplayName>JWT Issuer</DisplayName>
          <Protocol Name="None" />
          <OutputTokenFormat>JWT</OutputTokenFormat>
          <Metadata>
            <Item Key="client_id">{service:te}</Item>
            <Item Key="issuer_refresh_token_user_identity_claim_type">objectId</Item>
            <Item Key="SendTokenResponseBodyWithJsonNumbers">true</Item>
          </Metadata>
          <CryptographicKeys>
            <Key Id="issuer_secret" StorageReferenceId="B2C_1A_TokenSigningKeyContainer" />
            <Key Id="issuer_refresh_token_key" StorageReferenceId="B2C_1A_TokenEncryptionKeyContainer" />
          </CryptographicKeys>
          <InputClaims />
          <OutputClaims />
        </TechnicalProfile>
`

So for me the workaround is already in place (because policies were created only a couple of weeks ago, I guess).

Can anyone offer advice? Thanks!

**Comment by Dipan61241828** [comment] 2019-12-06 13:21
Hi @ugurcany 
Did you find any solution for this, i am facing same issue in my App.
Thanks!

**Comment by ugurcany** [comment] 2019-12-06 13:24
@Dipan61241828 Unfortunately not. We stopped using MSAL. You can follow the issue here as well: https://stackoverflow.com/questions/55576359/msal-for-android-fails-performing-b2c-login

**Comment by Dipan61241828** [comment] 2019-12-06 13:26
@iambmelt can you advice on this?
Thanks!

**Comment by iambmelt** [comment] 2019-12-12 23:35
I was recently able to repro this issue by sending an auth request with a scope that was not affiliated with any `access_token` -- B2C, it seems will still issue a response that contains no token.

When this happened I was able to repro -- note the lack of access token or expiry in the response. MSAL is currently unable to handle this.

```json
{
	"id_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsifQ.eyJleHAiOjE1NzYxOTYxOTQsIm5iZiI6MTU3NjE5MjU5NCwidmVyIjoiMS4wIiwiaXNzIjoiaHR0cHM6Ly9sb2dpbi5taWNyb3NvZnRvbmxpbmUuY29tL2M4ZjgzZjdjLWEyOGYtNGUwZC1hOTU2LTZlMGQyZGYzODI2Yi92Mi4wLyIsInN1YiI6IjE3NGE0YTg2LTUyZmItNDZmOC05YjA0LWJiMDIyZWNiYjg5NSIsImF1ZCI6ImUzYjlhZDc2LTk3NjMtNDgyNy1iMDg4LTgwYzdhNzg4OGY3OSIsImlhdCI6MTU3NjE5MjU5NCwiYXV0aF90aW1lIjoxNTc2MTkyNTk0LCJvaWQiOiIxNzRhNGE4Ni01MmZiLTQ2ZjgtOWIwNC1iYjAyMmVjYmI4OTUiLCJuYW1lIjoiQjJDIE1GQVRlc3QiLCJ0ZnAiOiJCMkNfMV9TSVNPUG9saWN5In0.PUgvnNTzXo7AXuwwNGhqYHUEj9aanfNJDoykHNV8M5SaazXXIRMEwOedMljy8FTGpDGFsbywbaw13FiSeEdf80MbRQXJNGmsGeJSM_vwyLuNL76TRrrQ7eGRLHIisk9YZoVWoWMTP623Nw6SK3kYzEr0Vyao5BCBRMelmmloszOCc5pPs3EZP2us-4NcfCOzND8pPBG8WCPbqCTkwqM7uF8YR4mBrXHmwSoB5e-f9OPdH7kQaqDmoXPPwddUznyFQDfnN7BeUFz6040kbX-wVwq-tc_m-bxPnJ5ch_y_BennjCfHcdpLQZNrx7pRpQscd8IMcuZoJR_rEJfQ-QA9Kw",
	"token_type": "Bearer",
	"not_before": 1576192594,
	"client_info": "eyJ1aWQiOiIxNzRhNGE4Ni01MmZiLTQ2ZjgtOWIwNC1iYjAyMmVjYmI4OTUtYjJjXzFfc2lzb3BvbGljeSIsInV0aWQiOiJjOGY4M2Y3Yy1hMjhmLTRlMGQtYTk1Ni02ZTBkMmRmMzgyNmIifQ",
	"scope": "",
	"refresh_token": "<not_shown>",
	"refresh_token_expires_in": 1209600
}
```

**Comment by sidlovskyy** [comment] 2020-04-11 10:44
I get the same behaviour with `com.microsoft.identity.client:msal:1.0.0` library. Can anyone please suggest.

**Comment by yoelhor** [comment] 2020-04-12 11:44
I'm facing same issue with `com.microsoft.identity.client:msal:1.3.0`

**Comment by iambmelt** [comment] 2020-09-22 22:46
Related:
https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1162

**Comment by iambmelt** [comment] 2021-01-27 18:34
Adding documentation to improve this experience here:
https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1291

**Comment by ukevgen** [comment] 2022-06-29 14:54
If you still have an error , try to go in Azure AD B2C -> android app -> Api access -> Click on Add -> Permitted Scopes and add scopes from your test web api

**Closed** 2022-07-17 23:04 UTC
Labels: Issue Triage, More Info, Cleanup
