### ISSUE TITLE
Crash on Android 7.0

### ISSUE THREAD

**Issue by xyzwilliamxyz** [AzureAD/microsoft-authentication-library-for-android#920] opened 2020-02-04 12:14 UTC
Hello,

I was testing MSAL on android 7.0 and I had this crash after completing an interactive registration authority.

```java
java.lang.RuntimeException: Error receiving broadcast Intent { act=cancel_interactive_request_action flg=0x10 } in com.microsoft.identity.common.internal.providers.oauth2.AuthorizationFragment$1@8c50a2
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.microsoft.identity.common.internal.providers.oauth2.AuthorizationStrategy.completeAuthorization(int, int, android.content.Intent)' on a null object reference
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.completeAcquireToken(LocalMSALController.java:205)
        at com.microsoft.identity.common.internal.controllers.InteractiveTokenCommand.notify(InteractiveTokenCommand.java:66)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher.completeInteractive(CommandDispatcher.java:468)
        at com.microsoft.identity.common.internal.providers.oauth2.AuthorizationFragment.sendResult(AuthorizationFragment.java:385)
        at com.microsoft.identity.common.internal.providers.oauth2.AuthorizationFragment.access$100(AuthorizationFragment.java:76)
        at com.microsoft.identity.common.internal.providers.oauth2.AuthorizationFragment$1.onReceive(AuthorizationFragment.java:143)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```
on android 7.1 it seems to be working, I didn't test it on older versions though. I will further investigate to check what I can find out.

Do you guys have an ideia of what it might be?

Thanks!

**Comment by shoatman** [comment] 2020-02-04 16:28
I haven't seen something like this before.  Possible to provide the repro steps.  I'm not sure I understood what an "interactive registration authority" was/is.  Is this B2C?  If so what kind of policy?  How is that flow completed in the UI?  (Seems to be coming back as a cancelled request)

**Comment by xyzwilliamxyz** [comment] 2020-02-05 12:09
Hi @shoatman, thanks for the reply.

Out of curiosity I decided to test this issue against the msal dev branch just in case this NPE is already fixed, and as it turns out, it's already fixed! Not execatly sure on which commit though. But it seems fine to me.

I'll close this issue, thanks for the help!

**Comment by xyzwilliamxyz** [comment] 2020-02-13 12:48
Hi @shoatman after we update our project to **msal:1.3.0**, this issue is happening again.

`
Fatal Exception: java.lang.RuntimeException
Error receiving broadcast Intent { act=cancel_interactive_request_action flg=0x10 launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } bqHint=1 } in com.microsoft.identity.common.internal.providers.oauth2.b$a@4a4baeb
android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:1195)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6682)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)

------------------------------------------------------

Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'void com.microsoft.identity.common.internal.providers.oauth2.f.a(int, int, android.content.Intent)' on a null object reference
com.microsoft.identity.client.internal.controllers.e.a (LocalMSALController.java:205)
com.microsoft.identity.common.internal.controllers.j.a (InteractiveTokenCommand.java:66)
com.microsoft.identity.common.internal.controllers.e.a (CommandDispatcher.java:468)
com.microsoft.identity.common.internal.providers.oauth2.b.a (AuthorizationFragment.java:407)
com.microsoft.identity.common.internal.providers.oauth2.b.a (AuthorizationFragment.java:78)
com.microsoft.identity.common.internal.providers.oauth2.b$a.onReceive (AuthorizationFragment.java:155)
android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:1185)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6682)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)`

it's odd because when were testing against the fork of the development branch it was fixed. Could it be something that didn't enter to this release? Or maybe an specific configuration that is present only on development branch?

Thanks!

**Comment by iambmelt** [comment] 2020-02-13 17:03
> Hi @shoatman after we update our project to **msal:1.3.0**, this issue is happening again.
> 
> `Fatal Exception: java.lang.RuntimeException
> Error receiving broadcast Intent { act=cancel_interactive_request_action flg=0x10 launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } bqHint=1 } in com.microsoft.identity.common.internal.providers.oauth2.b$a@4a4baeb
> android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:1195)
> android.os.Handler.handleCallback (Handler.java:751)
> android.os.Handler.dispatchMessage (Handler.java:95)
> android.os.Looper.loop (Looper.java:154)
> android.app.ActivityThread.main (ActivityThread.java:6682)
> java.lang.reflect.Method.invoke (Method.java)
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
> com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
> 
> Caused by java.lang.NullPointerException
> Attempt to invoke virtual method 'void com.microsoft.identity.common.internal.providers.oauth2.f.a(int, int, android.content.Intent)' on a null object reference
> com.microsoft.identity.client.internal.controllers.e.a (LocalMSALController.java:205)
> com.microsoft.identity.common.internal.controllers.j.a (InteractiveTokenCommand.java:66)
> com.microsoft.identity.common.internal.controllers.e.a (CommandDispatcher.java:468)
> com.microsoft.identity.common.internal.providers.oauth2.b.a (AuthorizationFragment.java:407)
> com.microsoft.identity.common.internal.providers.oauth2.b.a (AuthorizationFragment.java:78)
> com.microsoft.identity.common.internal.providers.oauth2.b$a.onReceive (AuthorizationFragment.java:155)
> android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:1185)
> android.os.Handler.handleCallback (Handler.java:751)
> android.os.Handler.dispatchMessage (Handler.java:95)
> android.os.Looper.loop (Looper.java:154)
> android.app.ActivityThread.main (ActivityThread.java:6682)
> java.lang.reflect.Method.invoke (Method.java)
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
> com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)`
> 
> it's odd because when we were testing against the fork of the development branch it was fixed. Could it be something that didn't enter to this release? Or maybe an specific configuration that is present only on development branch?
> 
> Thanks!

This looks like a ProGuard issue to me; I suggest disabling it to determine if this is the cause

**Comment by xyzwilliamxyz** [comment] 2020-02-13 18:29
Hi @iambmelt , thanks for the suggestion. I disabled pro-guard, but the crash still happens :/

**Comment by iambmelt** [comment] 2020-02-13 23:37
Thanks for verifying @xyzwilliamxyz 

Regarding your comment here:
>it's odd because when we were testing against the fork of the development branch it was fixed. Could it be something that didn't enter to this release? Or maybe an specific configuration that is present only on development branch?

Our `1.3.0` release was not cut from our development branch because _those_ bits haven't been fully tested. Instead, it was cut from our previous `1.2.0-hf1` release with various other fixes cherry-picked from dev.

Are you still seeing this issue _only_ on Android 7.0? Not 7.1 or higher? All devices? Specific devices?

**Comment by xyzwilliamxyz** [comment] 2020-02-14 13:21
> it was cut from our previous 1.2.0-hf1

@iambmelt I see, that should explain it. 

> Are you still seeing this issue only on Android 7.0? Not 7.1 or higher? All devices? Specific devices?

It's happening to Android 7.0 only on all devices

Android 7.1 onwards is working fine.

**Comment by shahzaibj** [comment] 2020-02-20 23:46
@xyzwilliamxyz We have a fix for this issue and I've opened up a PR [here](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/828). We are currently planning to start cutting an MSAL release some time next week. I'll keep you updated on the status of that.

**Comment by xyzwilliamxyz** [comment] 2020-02-20 23:55
@shahzaibj Great! Thank you very much. Looking forward to it!

**Closed** 2020-02-25 18:39 UTC
Labels: Bug - P2, Issue Triage

**Comment by shahzaibj** [comment] 2020-02-25 21:15
@xyzwilliamxyz This issue has been closed as the above linked PR has merged. I am currently working on getting the release process started (can take 2-4 days to complete). I'll give you an update once the release is available in Maven.

**Comment by shahzaibj** [comment] 2020-02-29 04:47
@xyzwilliamxyz The latest release of MSAL with this fix is available on Maven Central. The release version is `1.4.0`
