### ISSUE TITLE
MsalExceptionAdapter.java line 64

### ISSUE THREAD

**Issue by xyzwilliamxyz** [AzureAD/microsoft-authentication-library-for-android#1216] opened 2020-11-10 14:24 UTC
**Describe the bug**
Hi,

we're getting crashes from this error within MSAL. I remember we had to deal with something similar handling the token expired error a while ago by calling the **interactive acquire token**. But as this one is within the library itself, it's out of our reach.

**Smartphone (please complete the following information):**
 - Device: Moto Z (2) Play
 - Android Version: 8
 - MSAL Version: 1.5.4

**Stacktrace**
```
Fatal Exception: com.microsoft.identity.client.exception.MsalUiRequiredException: AADB2C90080: The provided grant has expired. Please re-authenticate and try again. Current time: 1604921912, Grant issued time: 1604684246, Grant expiration time: 1604770646
Correlation ID: *******-*******-*******-*******-*******
Timestamp: 2020-11-09 11:38:32Z

       at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:64)
       at com.microsoft.identity.client.PublicClientApplication$16.onError(PublicClientApplication.java:1673)
       at com.microsoft.identity.client.PublicClientApplication$16.onError(PublicClientApplication.java:1664)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:209)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6592)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)

```

**Comment by iambmelt** [comment] 2020-11-10 22:27
@xyzwilliamxyz It's not clear to me what the crash is from looking at your provided trace, as there seem to be some lines missing after the call to `MsalExceptionAdapter.msalExceptionFromBaseException`. What was the fatal exception and where did it occur? Can you repro this issue on newer versions of MSAL?

**Comment by xyzwilliamxyz** [comment] 2020-11-12 12:34
@iambmelt This is the fatal exception, also it's the full stacktrace reported by crashlytics. We don't know how to reproduce this one yet, but we see it on crashlytics from time to time.

**Comment by iambmelt** [comment] 2020-11-12 19:35
There's no `Caused by: ....` line? This is information needed: a `MsalUiRequiredException` is not/should not be a FATAL exception.

**Comment by xyzwilliamxyz** [comment] 2020-11-17 20:04
maybe it was a false positive from our crashlytics platform such as https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1200. We'll watch it closely to see if the error show up again.

**Comment by iambmelt** [comment] 2020-11-17 21:40
> maybe it was a false positive from our crashlytics platform such as #1200. We'll watch it closely to see if the error show up again.

Thanks for looking into it, @xyzwilliamxyz! I'll keep an eye out for any updates from you 👍

**Comment by iambmelt** [comment] 2020-12-01 23:42
Closing as false positive, thanks @xyzwilliamxyz

**Closed by iambmelt** 2020-12-01 23:42 UTC
Labels: More Info

**Comment by xyzwilliamxyz** [comment] 2020-12-11 13:28
hi @iambmelt , unfortunatelly this is still happening very often, but as a non-fatal (not the false positive crash anymore)

**Comment by xyzwilliamxyz** [comment] 2020-12-11 13:37
Here's an example of one of them:

**Non-fatal Exception:**

`
Non-fatal Exception: com.microsoft.identity.client.exception.MsalServiceException: referral:login_screen
       at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:74)
       at com.microsoft.identity.client.PublicClientApplication$16.onError(PublicClientApplication.java:1747)
       at com.microsoft.identity.client.PublicClientApplication$16.onError(PublicClientApplication.java:1738)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:340)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$1100(CommandDispatcher.java:74)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:322)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
`

**caused by:**

`
Caused by com.microsoft.identity.common.exception.ServiceException: referral:login_screen
       at com.microsoft.identity.common.internal.controllers.ExceptionAdapter.exceptionFromAcquireTokenResult(ExceptionAdapter.java:88)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.getCommandResultFromTokenResult(CommandDispatcher.java:405)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:298)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$200(CommandDispatcher.java:74)
       at com.microsoft.identity.common.internal.controllers.CommandDispatcher$4.run(CommandDispatcher.java:470)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
`

**Comment by iambmelt** [comment] 2020-12-11 20:52
@xyzwilliamxyz This `MsalServiceException: referral:login_screen` would be coming from your IEF/B2C app's backend, not from the library itself -- MSAL is passing the message from the service to the caller via `onError()`. I would suggest looking at your B2C service logs to determine the cause, as it looks like MSAL is simply relaying the error from elsewhere

**Comment by xyzwilliamxyz** [comment] 2020-12-14 14:50
@iambmelt I see. So the log actually just indicates that a backend service is failing.
