### ISSUE TITLE
Memory leak in CommandDispatcher

### ISSUE THREAD

**Issue by miragena** [AzureAD/microsoft-authentication-library-for-android#1955] opened 2023-11-17 07:05 UTC
I'm using: com.microsoft.identity.client:msal:4.7.0

When running with LeakCanary, it's detecting a leak:

- Please refer below trace path with detail reason (CommandDispatcher.sCommand) and attachment (hprof for more details)
┬───
│ GC Root: Thread object
│
├─ android.os.FileObserver$ObserverThread instance
│ Thread name: 'FileObserver'
│ ↓ Thread.contextClassLoader
├─ dalvik.system.PathClassLoader instance
│ ↓ ClassLoader.runtimeInternalObjects
├─ java.lang.Object[] array
│ ↓ Object[230]
├─ com.microsoft.identity.common.java.controllers.CommandDispatcher class
│ ↓ static CommandDispatcher.sCommand
├─ com.microsoft.identity.common.java.commands.InteractiveTokenCommand instance
│ Retaining 611 B in 27 objects
│ ↓ BaseCommand.parameters
├─ com.microsoft.identity.common.internal.commands.parameters.AndroidActivityInteractiveTokenCommandParameters instance
│ Retaining 312 B in 7 objects
│ activity instance of com.example.myapplication.MainActivity with mDestroyed = true
│ ↓ AndroidActivityInteractiveTokenCommandParameters.activity
╰→ com.example.myapplication.MainActivity instance
​ Retaining 959.4 kB in 21248 objects

I tried using WeakReference for .startAuthorizationFromActivity(), but the problem is still reproduced. 
 AcquireTokenParameters.Builder builder = new AcquireTokenParameters.Builder()
                .startAuthorizationFromActivity(new WeakReference<>(activity).get())
                .withLoginHint(loginHint)
                .withScopes(SCOPES);

 IMultipleAccountPublicClientApplication msalClient =
                    PublicClientApplication.createMultipleAccountPublicClientApplication(activity.getApplicationContext(),
                            getConfigResourceId());
            msalClient.acquireToken(new AcquireTokenParameters(builder));

Please help me check if the problem can be fixed. Thanks!

**Comment by negoe** [comment] 2024-02-16 18:13
Unable to reproduce, closing the issue.

**Closed as completed** 2024-02-16 18:13 UTC
