### ISSUE TITLE
Problem opening URL links

### ISSUE THREAD

**Issue by ralexandre-ciandt** [AzureAD/microsoft-authentication-library-for-android#1140] opened 2020-08-26 14:13 UTC
**Describe the bug**
We are receiving an error (thus killing the journey) when trying to open a link inside one of our journeys. It's live in production.

**Smartphone (please complete the following information):**
 - Device: All
 - Android Version: All
 - Browser Chrome
 - MSAL Version 1.5.4

**Stacktrace**
No crash, just an error from MSAL:
`The webView was redirected to an unsafe URL.
Redirect url scheme not SSL protected`

**To Reproduce**
1. We open one of our journeys for example: "Terms and conditions"
2. Click a link that should redirect to another URL (external URL)

**Expected behavior**
The link should open in the webview or redirect and open on chrome (or any default external browser)

**Actual Behavior**
MSAL returns an error and the app treats as a generic error

MSALServiceException also didn't return the clicked URL tried to open

**Comment by shahzaibj** [comment] 2020-08-26 16:38
Hi @ralexandre-ciandt Looks like you are hitting [this code path](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java#L135-L165). And it seems that the URL you are opening is not conforming to any of the supported formats here and falls into the last `else` block i.e. it is deemed as an invalid URL. I think you would want it to fall into the external website category [here](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java#L155). Also [see this](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/ui/webview/AzureActiveDirectoryWebViewClient.java#L176). This essentially means that the URL needs to start with `browser://`. See this, for instance: https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/adal/internal/AuthenticationConstants.java#L1035

Can you point me to the specific URL that you are redirecting to?

**Comment by ralexandre-ciandt** [comment] 2020-08-26 19:55
Thanks for the answer! We will be doing a few tests and let you know the results.

**Comment by ralexandre-ciandt** [comment] 2020-08-27 14:39
Just another question to include in our tests:

We have a journey with a "support telephone" number in it. It's a link and we are trying to make it open the dialer in the device when clicked by the user. It does work if we open the journey on Chrome, but is there a way we could achieve it in the app that is implementing MSAL?

In this case we get the same error, is there something like "dialer://" that should be in the URL?

**Comment by shahzaibj** [comment] 2020-09-02 00:45
@ralexandre-ciandt For telephone numbers, can you try something that starts with `tel:`?

**Comment by ralexandre-ciandt** [comment] 2020-09-02 13:32
Exactly! This is the one we are using and returning the error =/

**Comment by ralexandre-ciandt** [comment] 2020-10-16 12:58
Hi! We did the change to use "browser://" in the links inside the journey, it successfully opens the URL on Chrome! But...
MSAL returns a cancel operation without a parameter so we can skip it, closing the journey in the process. How could we handle this?

Thanks!

**Comment by hfrank-abi** [comment] 2020-11-05 13:53
Does this problem continue to effect the latest version of MSAL?

**Comment by shahzaibj** [comment] 2020-11-05 16:42
@ralexandre-ciandt What would be considered as completion of such a journey? Do we expect the user to get a token in this flow? It seems that the user leaves the token acquisition flow and goes to a browser URL to do other things.....hence the operation is being cancelled (as the user is not proceeding with obtaining a token). Can you provide more details on what the user is supposed to do when on this browser URL? and how do you know that the user is finished doing what they were doing in the browser and are meant to continue with the token request?

**Comment by ralexandre-ciandt** [comment] 2020-11-11 16:12
Hi!

It's returning a cancel operation when clicking the link, thus ending the current journey. So no other action is allowed in it anymore unless closed and reopened.
We also have been using this cancel to close the journey and open another flow.

Is there a way to this external URL event send an "error" instead of a "cancel"?

**Comment by xyzwilliamxyz** [comment] 2020-11-17 20:03
Same issue: https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1170

**Comment by xyzwilliamxyz** [comment] 2020-11-25 19:12
Hi, I tested this on the latest MSAL version (2.0.4) replacing **"https://"** by **"browser://"** and it was able to open the url! :+1: 

However, when I try to press back, it closes the webview and lose its state... could you guys check on that?

Also, there are some links that are **"mailto"**, and they don't work correctly when adding **"browser://"*, they open in the browse instead of the the default email app on the device.

**Comment by leonardochiaranda** [comment] 2020-12-11 13:07
@iambmelt @shahzaibj Hey, folks. Do you have any updates for us based on the comments from William? More specific for these following parts:

```
However, when I try to press back, it closes the webview and lose its state... could you guys check on that?

Also, there are some links that are "mailto", and they don't work correctly when adding **"browser://"*, they open in the browse instead of the the default email app on the device.
```

**Comment by shahzaibj** [comment] 2020-12-11 20:02
@xyzwilliamxyz @leonardochiaranda We will discuss within the team if we can implement specific handling for such links. Would you be able to provide us with a sample msal config file and test account so we can try out the user experience for these?

**Comment by ralexandre-ciandt** [comment] 2020-12-15 17:08
Hi @shahzaibj !

Do you want a sample of the app or the custom journey's file with the links configuration?

**Comment by wmiranda** [comment] 2020-12-17 03:00
@shahzaibj reinforcing ralexandre's question, what would be the "msal config file" you mentioned plz?

**Comment by shahzaibj** [comment] 2021-01-21 00:12
@wmiranda @ralexandre-ciandt @xyzwilliamxyz What you are seeing is expected behavior. When the user navigates to an external site then the token request operation is cancelled and hence you are seeing the on cancel callback being invoked. 

In terms of URL handling within webview, we write our code to be very specific about the types of URLs we handle because MSAL is an Authentication library with the primary purpose of providing tokens. So we don't handle any other URLs that we are know aren't meant to be used for token acquisition. 

Since you are using B2C, I would highly recommend using a browser specifically if you have setup Google as an IdP because Google Auth doesn't work in WebView. Furthermore, I would expect most browsers to have built-in support for handling `mailto` URLs so that aspect of your journey may also work better there.

**Comment by wilmerlm11** [comment] 2021-02-02 14:57
Hi @shahzaibj 
Tks for getting back to us.
I understand your point when you mention the main goal of Azure B2C as an IAM tool.
However, the scenario we are presenting must be a common situation for sure:

Our native app calls the Sign Up journey (B2C) and load the proper form in a webview.
During the registration flow, we must present the Terms & Conditions and the Privacy Policy.
It's a legal requirement for every Sign Up flow.

Within these texts, we have some external links we would like to call the native behavior...
For instance, links should be opened in a new browser window, mailto links must open the mail tool, tel links open the phone ready to dial, etc. After performing whatever the user wants, they must be able to switch back to our app in the same state as when they left. Without the need to restart the journey whatsoever.

I think the question here is... since MSAL intercepts these links, how to achieve the expected behaviors stated above?
I'm pretty sure it's a very common situation in many T&C and PP text, or even a simple contact us link or phone.

Please sry if I'm missing anything from your previous message, but we need the guidance to finally close this issue that have been pushing us away from the best customer experience.

Thank you!

**Comment by shahzaibj** [comment] 2021-02-08 23:16
@wilmerlm11 Have you looked into using BROWSER as the authorization user agent? That shouldn't have these problems.

**Comment by ralexandre-ciandt** [comment] 2021-02-22 13:43
Hi @shahzaibj !

We tested changing the links to **browser://www....** instead of **https://www....** but same result =/

**Comment by wilmerlm11** [comment] 2021-03-01 14:02
Hi @shahzaibj , any suggestion following @ralexandre-ciandt 's response?
We just want to be able to open these links in the browser, without closing the user journey.
It should be a common use case, considering links to T&C and PP (external pages).
Or even links to customer center's phone and email address (triggering phone's default behavior).

**Comment by GuyPaddock** [comment] 2021-08-18 23:24
We're having a similar problem here; really wish that the flow/journey was still open in the source app. Right now this leads to an error coming back to our app (and, therefore, an error back to the user).

**Comment by shahzaibj** [comment] 2021-08-18 23:41
@hamiltonha We should look into whether we want to support redirecting to unknown URLs from our WebViews. These are some links that are included in the Terms and Conditions pages of B2C User Journeys and from there they want to redirect to either other apps or other URLs. For instance, there may be a phone number link or email address in one these pages and the user expectation is that an appropriate app such as a Dialer or Mail application will be opened to handle the link. For now, we don't support such URLs in our broker and we return back an error.

**Comment by Luiz-Franco** [comment] 2022-03-16 12:58
Hi!

Any news on this?

**Comment by alexandru-spasenie** [comment] 2022-03-31 09:23
Interested on this also, we have a similar problem with our app as well. `The webView was redirected to an unsafe URL.` error when tapping certain links in Terms and conditions page.

**Closed** 2022-07-17 23:03 UTC
Labels: Issue Triage, More Info, Cleanup
