### ISSUE TITLE
AcquireTokenSilentAsync returns "Authority passed to silent parameters does not match with the cloud associated to the account."

### ISSUE THREAD

**Issue by Nasicus** [AzureAD/microsoft-authentication-library-for-android#882] opened 2020-01-02 15:51 UTC
I have a working app with a `b2c` configuration. Up until now I used the legacy b2c policy / authority URL's: e.g. `https://login.microsoftonline.com/tfp/<my-tenant>/B2C_1_SignUpPolicy`.

Today I tried to change them to the new URL style: e.g. `https://whatever.b2clogin.com/tfp/<my-tenant>/B2C_1_SignUpPolicy/`

And suddenly I get the mentioned error from above when calling `acquireTokenSilentAsync`.
I also compared with the sample app (https://github.com/Azure-Samples/ms-identity-android-java/) and couldn't find a real difference.

I also started investigating myself and dug quite deep and found the exception is thrown here:

```
public class AcquireTokenSilentOperationParameters extends OperationParameters {
//.... what ever
    @Override
    public void validate() throws ArgumentException {
        super.validate();

        if (mAccount == null) {
            Logger.warn(TAG, "The account set on silent operation parameters is NULL.");
        } else if (!authorityMatchesAccountEnvironment()) {
            throw new ArgumentException(
                    ArgumentException.ACQUIRE_TOKEN_SILENT_OPERATION_NAME,
                    ArgumentException.AUTHORITY_ARGUMENT_NAME,
                    "Authority passed to silent parameters does not match with the cloud associated to the account."
            );
        }
    }

    private boolean authorityMatchesAccountEnvironment() {
        final String methodName = ":authorityMatchesAccountEnvironment";
        try {
            if (!AzureActiveDirectory.isInitialized()) {
                performCloudDiscovery();
            }
            final AzureActiveDirectoryCloud cloud = AzureActiveDirectory.getAzureActiveDirectoryCloudFromHostName(mAccount.getEnvironment());
            return cloud != null && cloud.getPreferredNetworkHostName().equals(getAuthority().getAuthorityURL().getAuthority());
        } catch (IOException e) {
            Logger.error(
                    TAG + methodName,
                    "Unable to perform cloud discovery",
                    e);
            return false;
        }
    }
```

I debugged into the method ` final AzureActiveDirectoryCloud cloud = AzureActiveDirectory.getAzureActiveDirectoryCloudFromHostName(mAccount.getEnvironment());` which returns null, because it contains only the following hosts:
![image](https://user-images.githubusercontent.com/1086065/71676190-dff9ad80-2d7f-11ea-895c-c97935eb93b3.png)

my host (`whatever.b2clogin.com`) obviously doesn't match there and therefore `null ` is returned.

However I cannot believe that such a bug exists in this library. So I assume I configured something _wrong_. However I just can't point my finger on what it could be.

Here is my configuration:

```
{
  "client_id": "whatever",
  "redirect_uri": "msalbwhatever://auth",
  "broker_redirect_uri_registered": false,
  "authorities": [
    {
      "type": "B2C",
      "authority_url": "https://whatever.b2clogin.com/tfp/whatever.onmicrosoft.com/B2C_1_SignInSignUpPolicy/",
      "default": true
    },
    {
      "type": "B2C",
      "authority_url": "https://whatever.b2clogin.com/tfp/whatever.onmicrosoft.com/B2C_1_SignUpPolicy/"
    },
    {
      "type": "B2C",
      "authority_url": "https://whatever.b2clogin.com/tfp/whatever.onmicrosoft.com/B2C_1_ResetPasswordPolicy/"
    }
  ],
  "account_mode": "MULTIPLE",
  "logging": {
    "pii_enabled": true,
    "log_level": "VERBOSE",
    "logcat_enabled": true
  }
}
```

Any help would be greatly appreciated!

**Comment by shoatman** [comment] 2020-01-02 15:56
This looks like a bug to me.  There are authorities known to Microsoft and authorities known to you the developer (for example the B2C custom domains) and expressed to the library via configuration.  It's likely this won't get investigated in detail till next week.  Thanks very much for the detailed report.

**Comment by Nasicus** [comment] 2020-01-02 16:23
Thanks for the quick reply.
I also thought it was a bug first, but then I thought maybe I just misconfigured something wrong and it takes entirely the wrong code-path or it didn't populate the `aadClouds` correctly. Tomorrow I will (if I have time) also quickly try to run the sample and see if it works there...

PS: In the MSAL library for JS there is also a setting where you need to set `validateAuthority` to `false` for the custom b2c domains. See [here ](https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin) (bottom of page) and [here](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/blob/master/index.html). Maybe something similar exists or if not needs to be implmented for Android.

**Comment by shoatman** [comment] 2020-01-02 16:29
Android specifically removed support for validateAuthority as it's confusing to have to disable what is in fact a security feature for Azure AD B2C.  Authority validation was originally added to ADAL to ensure that a client didn't simply parse a 401 challenge and potentially use a malicious security token service.  In Android, we check the list of authorities known to Microsoft and known to you the developer (expressed via configuration) to determine whether or not it's safe to use an authority.  This particular code path isn't related to authority validation per-se... it's actually an account validation bug related to multiple Azure AD Clouds.  It just seems we forgot that B2C only exists in one cloud and that it can use a custom domain.

**Comment by iambmelt** [comment] 2020-01-02 21:42
@shahzaibj At a glance, this looks to be related to changes introduced in https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/714 -- do you have capacity to investigate here?

**Comment by shahzaibj** [comment] 2020-01-02 22:38
@Nasicus This is indeed a bug. As @shoatman pointed out we added this check for multiple cloud scenarios to ensure that developers pass an account that belongs in the correct cloud, and we forgot about the fact that B2C only exists in one cloud and can use custom domains.

I've opened up a PR to fix this issue. Here's the link: https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/764

**Comment by Nasicus** [comment] 2020-01-03 06:22
Thanks for the quick responses guys! I really appreciate transparency & communication like this :) 👍 

One more thing:
Once this get's merged do you already know if you plan do do a hotfix release or will it only be included in the next "regular" release (whenever this happens)?

**Comment by shahzaibj** [comment] 2020-01-03 19:38
@Nasicus we are considering doing a hotfix release for this and we will be discussing it in our scrum on Monday. We will provide you an update on our plan on Monday after our scrum.

**Comment by shahzaibj** [comment] 2020-01-06 21:43
@Nasicus We have decided to do a hotfix release for this issue. We have started the release process and the entire release process will take about 1-2 days to complete. We will give you an update once the release is available.

**Comment by shahzaibj** [comment] 2020-01-07 18:18
@Nasicus A new release of MSAL with the hotfix has been released to Maven Central and is available for use. The version number of this release is `1.1.0-hf1`.

Thank you so much for opening the issue with a detailed report and helping us make the library better.

I am going to close this issue now as the release is available on Maven Central. Feel free to reopen if you are still experiencing issues.

**Comment by shahzaibj** [comment] 2020-01-07 18:20
Fixed by [common PR 767](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/767)

**Closed by shahzaibj** 2020-01-07 18:20 UTC
Labels: Bug - P1, Issue Triage

**Comment by Nasicus** [comment] 2020-01-08 07:36
Tested this just now and I can confirm it's now working as expected.

**Comment by iambmelt** [comment] 2020-01-08 17:59
@Nasicus Great to hear - thanks for confirming!

/cc @shahzaibj

**Comment by duyvt88** [comment] 2020-06-12 17:41
Hi @Nasicus, @shahzaibj 
I got the same issue "Provided authority is not known.  MSAL will only make requests to known authorities". I added "implementation 'com.microsoft.identity.client:msal:1.1.0-hf1'" into build.gradle file but still got the same issue. How can I get the version 1.1.0-hf1? 

Many thanks,

**Comment by shahzaibj** [comment] 2020-06-12 17:46
Hi @duyvt88 If you are using B2C, then you need to declare your authorities in the MSAL configuration file for them to be known by MSAL - otherwise you would get this error. Did you declare your authorities in the config file? The instructions to do so are here: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-android-b2c#configure-known-authorities-and-redirect-uri

**Comment by duyvt88** [comment] 2020-06-12 18:03
> Hi @duyvt88 If you are using B2C, then you need to declare your authorities in the MSAL configuration file for them to be known by MSAL - otherwise you would get this error. Did you declare your authorities in the config file? The instructions to do so are here: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-android-b2c#configure-known-authorities-and-redirect-uri

@shahzaibj I fixed it. Thank you very much :)

**Comment by shahzaibj** [comment] 2020-06-12 18:05
@duyvt88 I'm glad to hear that 😊

**Comment by praveenkg85** [comment] 2020-07-13 05:35
I am facing the same issue. Authority Type is "AAD". Please suggest how can it be resolved.
{
  "client_id" : "XXX",
  "authorization_user_agent" : "DEFAULT",
  "redirect_uri" : "XXX",
  "account_mode" : "SINGLE",
  "environment" : "PreProduction",
  "authorities" : [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADandPersonalMicrosoftAccount",
        "tenant_id": "common"
      },
      "default": true,
      "authority_url" : "https://login.microsoftonline.com/<id>/oauth2/authorize"
    }
  ]
}

**Comment by iambmelt** [comment] 2020-07-13 17:29
> @shahzaibj , @iambmelt , I am facing the same issue. Authority Type is "AAD". Please suggest how can it be resolved.
> 
> ```json
> {
>   "client_id" : "XXX",
>   "authorization_user_agent" : "DEFAULT",
>   "redirect_uri" : "XXX",
>   "account_mode" : "SINGLE",
>   "environment" : "PreProduction",
>   "authorities" : [
>     {
>       "type": "AAD",
>       "audience": {
>         "type": "AzureADandPersonalMicrosoftAccount",
>         "tenant_id": "common"
>       },
>       "default": true,
>       "authority_url" : "https://login.microsoftonline.com/<id>/oauth2/authorize"
>     }
>   ]
> }
> ```

@praveenkg85 Your configuration contains conflicting values around PPE vs prod, and declaring a tenant + authority url. Documentation on creating your configuration can be found [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration)

**Comment by praveenkg85** [comment] 2020-07-14 04:01
@iambmelt , I followed the same approach, but no luck.
{
  "client_id" : "XXX",
  "authorization_user_agent" : "DEFAULT",
  "redirect_uri" : "XXX",
  "account_mode" : "SINGLE",
  "environment" : "PreProduction",
  "authorities" : [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADandPersonalMicrosoftAccount"
      },
      "default": true
    }
  ]
}

The Authority is used:
https://login.microsoftonline.com/<id>
https://login.microsoftonline.com/common

None of them worked.
I tried to add "broker_redirect_uri_registered": true/false, but no help.

Please check, where is the issue.

**Comment by iambmelt** [comment] 2020-07-14 20:58
@praveenkg85 I suspect your app is not registered in the PreProduction `environment`. You'll notice this property isn't documented so I am immediately suspicious to its use
