### ISSUE TITLE
E/MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig:  OpenId Provider Configuration metadata failed to load with status: 404 Android 29

### ISSUE THREAD

**Issue by CODE1LT** [AzureAD/microsoft-authentication-library-for-android#1148] opened 2020-09-04 06:07 UTC
Tested on Android Emulator, API 21 and 29 (latest build), MSAL versions 1.4.1, 1.5.5 and 1.6. Same problem on all versions.

**Description:**

When calling mSingleAccountApp.acquireTokenSilent(getScopes(), AUTHORITY_SIGN_IN_PROD).accessToken I get this error (see below). 
AUTHORITY_SIGN_IN_PROD ="https://xxx/tfp/yyy/B2C_1A_JITMigraion_signup_signin/" (where xxx and yyy I wrote just to hide actual path details)

**Steps to reproduce/Actual behaviour:**

The reason for it is that MSAL class OpenIdProviderConfigurationClient in method public synchronized OpenIdProviderConfiguration loadOpenIdProviderConfiguration() transforms my AUTHORITY_SIGN_IN_PROD url into this one: "https://xxx/%2Ftfp%2Fyyy%2FB2C_1A_JITMigraion_signup_signin%2F/v2.0/.well-known/openid-configuration". The issue is in this part “/%2Ftfp%2F” and HTTP client after calling this url give me 404 response code. If I fix this url myself to this one “https://xxx/tfp/yyy/B2C_1A_JITMigraion_signup_signin/v2.0/.well-known/openid-configuration” and call it in the browser, it works just fine, and configuration is retrieved. So I assume it is internal MSAL library bug.

**Expected behavior:**

Msal method loadOpenIdProviderConfiguration() do not change (do not add unnecessary %2F symbols to) signup/signin url.

**Error details**
```
E/MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig:  [2020-09-03 06:33:43 - {"thread_id":"618","correlation_id":"e22dcef4-67c8-4298-9691-a1cf05ded788"}] OpenId Provider Configuration metadata failed to load with status: 404 Android 29
    com.microsoft.identity.common.exception.ServiceException: OpenId Provider Configuration metadata failed to load with status: 404
        at com.microsoft.identity.common.internal.providers.oauth2.OpenIdProviderConfigurationClient.loadOpenIdProviderConfiguration(OpenIdProviderConfigurationClient.java:147)
        at com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.MicrosoftStsOAuth2Configuration.getOpenIdWellKnownConfig(MicrosoftStsOAuth2Configuration.java:156)
        at com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.MicrosoftStsOAuth2Configuration.getOpenIdWellKnownConfigForAuthority(MicrosoftStsOAuth2Configuration.java:132)
        at com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.MicrosoftStsOAuth2Configuration.getTokenEndpoint(MicrosoftStsOAuth2Configuration.java:68)
        at com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.MicrosoftStsOAuth2Strategy.<init>(MicrosoftStsOAuth2Strategy.java:112)
        at com.microsoft.identity.common.internal.authorities.AzureActiveDirectoryB2CAuthority.createOAuth2Strategy(AzureActiveDirectoryB2CAuthority.java:91)
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.acquireTokenSilent(LocalMSALController.java:282)
        at com.microsoft.identity.common.internal.commands.SilentTokenCommand.execute(SilentTokenCommand.java:75)
        at com.microsoft.identity.common.internal.commands.SilentTokenCommand.execute(SilentTokenCommand.java:41)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:170)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$200(CommandDispatcher.java:66)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$2.run(CommandDispatcher.java:127)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by shahzaibj** [comment] 2020-09-04 20:13
@CODE1LT Thanks for reporting the issue. This will be fixed in the next MSAL release scheduled to be released on September 14. I will provide an update here with the version number once the release hits Maven Central.

**Comment by shahzaibj** [comment] 2020-09-16 19:01
@CODE1LT Closing this issue as it should now be resolved on the [latest MSAL release v2.0.0](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v2.0.0). Please update the library to the latest version. Feel free to reopen if you still experience issues.

**Comment by vjsystematix** [comment] 2020-09-28 17:21
@CODE1LT  Increase the library version of MSAL as suggested by you, but still, get the below error from the cloud API.

Error :- E/MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig:  [2020-09-28 16:23:59 - {"thread_id":"2519","correlation_id":"05f1f4b9-fa86-4a99-a08e-49bad344b2c9"}] OpenId Provider Configuration metadata failed to load with status: 404 Android 29
    com.microsoft.identity.common.exception.ServiceException: OpenId Provider Configuration metadata failed to load with status: 404

Can you please help me out this what are the steps that need to be taken?

FYI:- I will run the android app on android 10.

Thanks

**Comment by iambmelt** [comment] 2020-09-29 01:51
Reopening issue

**Comment by shahzaibj** [comment] 2020-10-02 21:06
@CODE1LT We removed this code in the latest version altogether, so we don't expect you to even hit this code path. Can you confirm which version of MSAL you're on?

**Comment by shahzaibj** [comment] 2020-10-07 16:59
@CODE1LT Do you still have this issue?

**Comment by anandlingaraj** [comment] 2020-11-25 23:34
Studio 4.1.1
Release R

 implementation 'com.microsoft.identity.client:msal:1.4.0'
 implementation 'com.microsoft.graph:microsoft-graph:1.5.+'

 Unable to upgrade to 2.0.0 as it throws device display error due to depency missing in Maven PoM

Post Authentication getting same error:

E/MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig:  [2020-11-25 23:20:58 - {"thread_id":"556","correlation_id":"be299a70-0d0b-43b6-8a1a-707ac6340076"}] OpenId Provider Configuration metadata failed to load with status: 404 Android 30
    com.microsoft.identity.common.exception.ServiceException: OpenId Provider Configuration metadata failed to load with status: 404
        at com.microsoft.identity.common.internal.providers.oauth2.OpenIdProviderConfigurationClient.loadOpenIdProviderConfiguration(OpenIdProviderConfigurationClient.java:147)
        at com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.MicrosoftStsOAuth2Configuration.getOpenIdWellKnownConfig(MicrosoftStsOAuth2Configuration.java:156)
        at com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.MicrosoftStsOAuth2Configuration.getOpenIdWellKnownConfigForAuthority(MicrosoftStsOAuth2Configuration.java:132)
        at com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.MicrosoftStsOAuth2Configuration.getTokenEndpoint(MicrosoftStsOAuth2Configuration.java:68)
        at com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.MicrosoftStsOAuth2Strategy.<init>(MicrosoftStsOAuth2Strategy.java:112)
        at com.microsoft.identity.common.internal.authorities.AzureActiveDirectoryB2CAuthority.createOAuth2Strategy(AzureActiveDirectoryB2CAuthority.java:78)
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.acquireToken(LocalMSALController.java:123)
        at com.microsoft.identity.common.internal.controllers.InteractiveTokenCommand.execute(InteractiveTokenCommand.java:51)
        at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:310)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by anandlingaraj** [comment] 2020-11-25 23:35
> @CODE1LT Closing this issue as it should now be resolved on the [latest MSAL release v2.0.0](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v2.0.0). Please update the library to the latest version. Feel free to reopen if you still experience issues.

If 2.0.0 the application cannot compile

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.microsoft.device.display:display-mask:0.3.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/microsoft/device/display/display-mask/0.3.0/display-mask-0.3.0.pom
       - https://jcenter.bintray.com/com/microsoft/device/display/display-mask/0.3.0/display-mask-0.3.0.pom
       - https://repo.maven.apache.org/maven2/com/microsoft/device/display/display-mask/0.3.0/display-mask-0.3.0.pom
     Required by:
         project :app > com.microsoft.identity.client:msal:2.0.0 > com.microsoft.identity:common:3.0.1

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by anandlingaraj** [comment] 2020-11-25 23:37
<img width="947" alt="Screen Shot 2020-11-25 at 6 36 33 PM" src="https://user-images.githubusercontent.com/49498061/100291999-487beb00-2f4d-11eb-9248-7d2730a9a299.png">

**Comment by anandlingaraj** [comment] 2020-11-25 23:39
<img width="990" alt="Screen Shot 2020-11-25 at 6 39 29 PM" src="https://user-images.githubusercontent.com/49498061/100292105-942e9480-2f4d-11eb-8934-f6b321769cfc.png">

**Comment by shahzaibj** [comment] 2020-11-25 23:42
@anandlingaraj That seems to be a different issue (unrelated to the Well Known Config issue that is discussed here). It seems that you are running an issue with Maven / Dependencies. The display mask dependency was added back in MSAL release 1.5.0 and we have instructions written there.
https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v1.5.0

There are also instructions on our readme here: https://github.com/AzureAD/microsoft-authentication-library-for-android#step-1-declare-dependency-on-msal

Can you follow those instructions? That should resolve your issue. Thanks!

**Comment by shahzaibj** [comment] 2020-12-03 04:06
Closing due to inactivity and the issue should already be resolved on the latest version of MSAL.

**Closed by shahzaibj** 2020-12-03 04:06 UTC
Labels: Bug - P2, Issue Triage

**Comment by ashu2451990** [comment] 2022-03-06 18:02
Getting again same issue as below :

2022-03-06 23:31:01.199 22188-22188/ E/App: Authentication error
    com.microsoft.identity.client.exception.MsalServiceException: OpenId Provider Configuration metadata failed to load with status: 400
        at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:74)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:350)
        at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:336)
        at com.microsoft.identity.client.PublicClientApplication$15$1.run(PublicClientApplication.java:1645)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: com.microsoft.identity.common.exception.ServiceException: OpenId Provider Configuration metadata failed to load with status: 400
        at com.microsoft.identity.common.internal.providers.oauth2.OpenIdProviderConfigurationClient.loadOpenIdProviderConfiguration(OpenIdProviderConfigurationClient.java:149)
        at com.microsoft.identity.common.internal.authorities.AzureActiveDirectoryAudience.loadOpenIdProviderConfigurationMetadata(AzureActiveDirectoryAudience.java:152)
        at com.microsoft.identity.common.internal.authorities.AzureActiveDirectoryAudience.getTenantUuidForAlias(AzureActiveDirectoryAudience.java:95)
        at com.microsoft.identity.client.PublicClientApplication.selectAccountRecordForTokenRequest(PublicClientApplication.java:1715)
        at com.microsoft.identity.client.PublicClientApplication.access$400(PublicClientApplication.java:202)
        at com.microsoft.identity.client.PublicClientApplication$15.run(PublicClientApplication.java:1611)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
2022-03-06 23:31:01.202 22188-22188/ E/App: Authentication error com.microsoft.identity.client.exception.MsalServiceException: OpenId Provider Configuration metadata failed to load with status: 400

**Comment by sup0808** [comment] 2022-08-31 09:59
@shahzaibj
I am facing this issue in my app .

 MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: com.microsoft.identity.common.exception.ServiceException: OpenId Provider Configuration metadata failed to load with status: 404
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: 	at com.microsoft.identity.common.internal.providers.oauth2.OpenIdProviderConfigurationClient.loadOpenIdProviderConfiguration(OpenIdProviderConfigurationClient.java:147)
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: 	at com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.MicrosoftStsOAuth2Configuration.getOpenIdWellKnownConfig(MicrosoftStsOAuth2Configuration.java:156)
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: 	at com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.MicrosoftStsOAuth2Configuration.getOpenIdWellKnownConfigForAuthority(MicrosoftStsOAuth2Configuration.java:132)
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: 	at com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.MicrosoftStsOAuth2Configuration.getTokenEndpoint(MicrosoftStsOAuth2Configuration.java:68)
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: 	at com.microsoft.identity.common.internal.providers.microsoft.microsoftsts.MicrosoftStsOAuth2Strategy.<init>(MicrosoftStsOAuth2Strategy.java:112)
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: 	at com.microsoft.identity.common.internal.authorities.AzureActiveDirectoryB2CAuthority.createOAuth2Strategy(AzureActiveDirectoryB2CAuthority.java:78)
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: 	at com.microsoft.identity.client.internal.controllers.LocalMSALController.acquireTokenSilent(LocalMSALController.java:258)
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: 	at com.microsoft.identity.common.internal.controllers.TokenCommand.execute(TokenCommand.java:70)
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: 	at com.microsoft.identity.common.internal.controllers.TokenCommand.execute(TokenCommand.java:39)
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: 	at com.microsoft.identity.common.internal.controllers.CommandDispatcher.executeCommand(CommandDispatcher.java:145)
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: 	at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$200(CommandDispatcher.java:60)
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: 	at com.microsoft.identity.common.internal.controllers.CommandDispatcher$1.run(CommandDispatcher.java:102)
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: 	at java.lang.Thread.run(Thread.java:1012)


I am using latest version of MSAL 
implementation ("com.microsoft.identity.client:msal:2.0.8")

**Comment by sup0808** [comment] 2022-08-31 09:59
@shahzaibj  Please suggest the solution.

**Comment by sup0808** [comment] 2022-08-31 10:00
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig:  [2022-08-30 05:38:38 - {"thread_id":"487471","correlation_id":"c8c29d11-4246-41fb-afd4-03faa1836556"}] OpenId Provider Configuration metadata failed to load with status: 404 Android 31
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: com.microsoft.identity.common.exception.ServiceException: OpenId Provider Configuration metadata failed to load with status: 404
08-30 11:08:38.984 27933 28160 E MicrosoftStsOAuth2Configuration:getOpenIdWellKnownConfig: 	at com.microsoft.identity.common.internal.providers.oauth2.OpenIdProviderConfigurationClient.loadOpenIdProviderConfiguration(OpenIdProviderConfigurationClient.java:147)
