### ISSUE TITLE
If BrokerActivity destroyed, account chooser activity can spin indefinitely

### ISSUE THREAD

**Issue by codylund** [AzureAD/microsoft-authentication-library-for-android#1631] opened 2022-05-27 17:11 UTC
**Describe the bug**
`BrokerActivity` is not robust to the `Activity.onDestroy()` lifecycle event which [the system may trigger at arbitrary times](https://developer.android.com/reference/android/app/Activity#onDestroy()) while `BrokerActivity` is in the background to temporarily preserve system resources. Contrary to the current assumptions in `BrokerActivity`, `onDestroy()` may be called while the interactive authentication session is in a healthy state. Rather than continue waiting for an auth result from the broker, `BrokerActivity` assumes the session is unhealthy and terminates with an error. This can leave any MSAL activities started on top of `BrokerActivity` in an unstable state.

In my own local repros, I have observed this to result in an infinite spinner on the account picker screen. From our app's perspective, we have received an error result, but our activity never resumes because the user is stuck on an infinite spinner on the account picker screen.

**Smartphone (please complete the following information):**
 - Device: Pixel 4 XL
 - Android Version: 12
 - Brokered auth with CP
 - MSAL Version: 3.0.2
 - 
**To Reproduce**
Unfortunately, there is no straightforward repro for this issue and it occurs intermittently. It does not repro with "Don't keep activities" turned on, because this repro requires that only the `BrokerActivity` is destroyed. It may be possible to replicate this in an Espresso test environment, however.

**Expected behavior**
`BrokerActivity` is resilient to system-triggered `onDestroy()` invocations and the interactive auth session does not deadlock on infinite spinner.

**Actual Behavior**
If `BrokerActivity` is destroyed while doing interactive auth, the user can become stuck on the account chooser activity's infinite spinner.

**Comment by iamgusain** [comment] 2022-08-22 17:38
Marking this as closed, as we are not able to reproduce it.
More details added to the bug https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1932240

**Closed as completed by iamgusain** 2022-08-22 17:38 UTC
