### ISSUE TITLE
StrictMode errors due to untagged sockets.

### ISSUE THREAD

**Issue by wyber** [AzureAD/microsoft-authentication-library-for-android#449] opened 2018-11-02 19:16 UTC
Similar to issue: https://github.com/square/okhttp/issues/3537

StrictMode with VmPolicy detectAll() in Android O results in the stack below. A workaround is mentioned in the issue above. See https://github.com/square/okhttp/issues/3537#issuecomment-328644595

```
java.lang.Throwable: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
        at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2012)
        at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:78)
        at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:47)
        at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:310)
        at libcore.io.IoBridge.socket(IoBridge.java:667)
        at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:116)
        at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:98)
        at java.net.Socket.createImpl(Socket.java:484)
        at java.net.Socket.getImpl(Socket.java:547)
        at java.net.Socket.setSoTimeout(Socket.java:1175)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:139)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
        at com.microsoft.identity.common.internal.net.HttpRequest.executeHttpSend(HttpRequest.java:189)
        at com.microsoft.identity.common.internal.net.HttpRequest.sendWithRetry(HttpRequest.java:162)
        at com.microsoft.identity.common.internal.net.HttpRequest.send(HttpRequest.java:143)
        at com.microsoft.identity.common.internal.net.HttpRequest.sendGet(HttpRequest.java:134)
        at com.microsoft.identity.common.internal.providers.microsoft.azureactivedirectory.AzureActiveDirectory.performCloudDiscovery(AzureActiveDirectory.java:146)
        at com.microsoft.identity.client.internal.authorities.Authority.performCloudDiscovery(Authority.java:196)
        at com.microsoft.identity.client.internal.authorities.Authority.getKnownAuthorityResult(Authority.java:261)
        at com.microsoft.identity.client.internal.controllers.LocalMSALController.acquireToken(LocalMSALController.java:88)
        at com.microsoft.identity.client.internal.controllers.MSALInteractiveTokenCommand.execute(MSALInteractiveTokenCommand.java:60)
        at com.microsoft.identity.client.internal.controllers.MSALApiDispatcher$1.run(MSALApiDispatcher.java:70)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by shoatman** [comment] 2018-11-02 19:18
@danieldobalian - Please add this to the backlog and let's discuss prioritization.

**Comment by iambmelt** [comment] 2019-01-29 00:58
Closing as duplicate of #317

**Closed by iambmelt** 2019-01-29 00:58 UTC
Labels: Feature Request
