### ISSUE TITLE
signin error specifically in one device only

### ISSUE THREAD

**Issue by rupalgohel** [AzureAD/microsoft-authentication-library-for-android#534] opened 2019-02-21 06:50 UTC
Sign in users and call the Microsoft Graph API from an Android app: not able to sing in on perticular one device

https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-android#help-and-support

Using the same credential, I am able to signin in anyother device, but not able to sign in particularly one of the device. It seems device specific issue.

Below are the device issue.

Device Name: OPPO R17
Model: CPH1879
ColorOS: V5.2.1
Android Version: 8.1.0

Got below response from azure api
`com.microsoft.identity.client.exception.MsalClientException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference`

**Comment by iambmelt** [comment] 2019-02-21 17:58
Hi @rupalgohel - I suspect that this issue may be caching related, but not enough stack trace information is provided to discern exactly what's going wrong. Is there any additional logging you could provide us to help troubleshoot this issue?

Is your issue a duplicate of #495? We've seen issues related to encryption and the use of `KeyStore` across varying device manufacturers

**Closed** 2019-03-20 05:34 UTC
Labels: Investigate
